# frozen_string_literal: true

# Copyright (c) 2025 Kenshi Muto, Masayoshi Takahashi
#
# This program is free software.
# You can distribute or modify this program under the terms of
# the GNU LGPL, Lesser General Public License version 2.1.

require 'review/renderer/base'
require 'review/ast/caption_node'
require 'review/renderer/rendering_context'
require 'review/renderer/formatters/html_reference_formatter'
require 'review/renderer/html/inline_context'
require 'review/renderer/html/inline_element_handler'
require 'review/htmlutils'
require 'review/textutils'
require 'review/escape_utils'
require 'review/highlighter'
require 'review/sec_counter'
require 'review/i18n'
require 'review/loggable'
require 'review/ast/indexer'
require 'review/ast/compiler'
require 'review/template'
require 'review/img_math'
require 'digest'

module ReVIEW
  module Renderer
    class HtmlRenderer < Base
      include ReVIEW::HTMLUtils
      include ReVIEW::TextUtils
      include ReVIEW::EscapeUtils
      include ReVIEW::Loggable

      attr_reader :chapter, :book

      def initialize(chapter, img_math: nil)
        super(chapter)

        # Initialize logger like HTMLBuilder for error handling
        @logger = ReVIEW.logger

        # Initialize section counter like HTMLBuilder (handle nil chapter)
        @sec_counter = @chapter ? SecCounter.new(5, @chapter) : nil

        # Initialize template variables like HTMLBuilder
        @javascripts = []
        @body_ext = ''

        # Initialize ImgMath for equation image generation (like Builder)
        # Accept shared instance or create new one
        @img_math = img_math || ReVIEW::ImgMath.new(config)

        # Initialize RenderingContext for cleaner state management
        @rendering_context = RenderingContext.new(:document)

        # Initialize HTML-specific inline context and inline element handler
        @inline_context = Html::InlineContext.new(config: config, book: book, chapter: chapter, renderer: self, img_math: @img_math)
        @inline_element_handler = Html::InlineElementHandler.new(@inline_context)
        @reference_formatter = Formatters::HtmlReferenceFormatter.new(config: config)
      end

      def visit_document(node)
        render_children(node)
      end

      def visit_headline(node)
        level = node.level
        caption = render_caption_markup(node.caption_node)

        if node.nonum? || node.notoc? || node.nodisp?
          # Use label if provided, otherwise use auto_id generated by Compiler
          id = normalize_id(node.label || node.auto_id)

          spacing_before = level > 1 ? "\n" : ''

          if node.nodisp?
            a_tag = %Q(<a id="#{id}" />)
            %Q(#{spacing_before}#{a_tag}<h#{level} id="#{id}" hidden="true">#{caption}</h#{level}>\n)
          elsif node.notoc?
            %Q(#{spacing_before}<h#{level} id="#{id}" notoc="true">#{caption}</h#{level}>\n)
          else
            %Q(#{spacing_before}<h#{level} id="#{id}">#{caption}</h#{level}>\n)
          end
        else
          prefix, anchor = headline_prefix(level)

          anchor_html = anchor ? %Q(<a id="h#{anchor}"></a>) : ''
          secno_html = prefix ? %Q(<span class="secno">#{prefix}</span>) : ''
          spacing_before = level > 1 ? "\n" : ''

          if node.label
            label_id = normalize_id(node.label)
            %Q(#{spacing_before}<h#{level} id="#{label_id}">#{anchor_html}#{secno_html}#{caption}</h#{level}>\n)
          else
            "#{spacing_before}<h#{level}>#{anchor_html}#{secno_html}#{caption}</h#{level}>\n"
          end
        end
      end

      def visit_paragraph(node)
        content = render_children(node)
        content = join_paragraph_lines(content).strip

        # Check for noindent attribute
        if node.attribute?(:noindent)
          %Q(<p class="noindent">#{content}</p>\n)
        else
          "<p>#{content}</p>\n"
        end
      end

      # Join paragraph lines according to join_lines_by_lang setting
      # This matches HTMLBuilder's join_lines_to_paragraph behavior
      #
      # @param content [String] paragraph content with newlines
      # @return [String] processed content with lines joined appropriately
      def join_paragraph_lines(content)
        if config['join_lines_by_lang']
          # Split by newlines to get individual lines
          lines = content.split("\n")

          # Add spaces between lines based on language rules
          lazy = true
          lang = config['language'] || 'ja'
          0.upto(lines.size - 2) do |n|
            if add_space?(lines[n], lines[n + 1], lang, lazy)
              lines[n] += ' '
            end
          end
          lines.join
        else
          # Default: just remove newlines (no space added)
          content.gsub(/\n+/, '')
        end
      end

      def visit_list(node)
        tag = case node.list_type
              when :ul
                'ul'
              when :ol
                'ol'
              when :dl
                'dl'
              else
                raise NotImplementedError, "HTMLRenderer does not support list_type #{node.list_type}."
              end

        # Check for start_number for ordered lists
        # Only output start attribute if it's not the default value (1)
        start_attr = ''
        if node.list_type == :ol && node.start_number && node.start_number != 1
          start_attr = %Q( start="#{node.start_number}")
        end

        content = render_children(node)
        # Format list items with proper line breaks like HTMLBuilder
        formatted_content = content.gsub(%r{</li>(?=<li>)}, "</li>\n")
        formatted_content = formatted_content.gsub(/<li>([^<]*)<ul>/, "<li>\\1<ul>\n")
        formatted_content = formatted_content.gsub('</ul></li>', "</ul>\n</li>")
        "<#{tag}#{start_attr}>\n#{formatted_content}\n</#{tag}>\n"
      end

      def visit_list_item(node)
        # Get parent list to determine list type
        parent_list = node.parent
        if parent_list && parent_list.list_type == :dl
          # Definition list item - use term_children for term like LaTeXRenderer
          term = if node.term_children&.any?
                   node.term_children.map { |child| visit(child) }.join
                 else
                   ''
                 end

          # Children contain the definition content
          # Join all children into a single dd like HTMLBuilder does with join_lines_to_paragraph
          if node.children.empty?
            # Only term, no definition - add empty dd like HTMLBuilder
            "<dt>#{term}</dt><dd></dd>"
          else
            # Render all child content and join together
            definition_parts = node.children.map { |child| visit(child) }
            # Join multiple paragraphs/text into single dd content, removing <p> tags
            definition_content = definition_parts.map { |part| part.gsub(%r{</?p[^>]*>}, '').strip }.join
            "<dt>#{term}</dt><dd>#{definition_content}</dd>"
          end
        else
          # Regular list item
          content = render_children(node)
          "<li>#{content}</li>"
        end
      end

      def visit_text(node)
        escape_content(node.content.to_s)
      end

      def visit_inline(node)
        content = render_children(node)
        render_inline_element(node.inline_type, content, node)
      end

      def visit_code_line(node)
        # Process each line like HTMLBuilder - detab and preserve exact content
        # Add newline like other renderers (LaTeX, Markdown, Top) do
        line_content = render_children(node)
        detab(line_content) + "\n"
      end

      def visit_table(node)
        # Check if this is an imgtable - handle as image like HTMLBuilder
        if node.table_type == :imgtable
          return render_imgtable(node)
        end

        id_attr = node.id ? %Q( id="#{normalize_id(node.id)}") : ''

        # Process caption with proper context management
        caption_html = if node.caption_node
                         @rendering_context.with_child_context(:caption) do |caption_context|
                           caption_content = render_caption_with_context(node.caption_node, caption_context)
                           # Generate table number like HTMLBuilder using chapter table index
                           table_number = if node.id
                                            generate_table_header(node.id, caption_content)
                                          else
                                            # No ID - just use caption without numbering
                                            caption_content
                                          end
                           %Q(<p class="caption">#{table_number}</p>
)
                         end
                       else
                         ''
                       end

        # Process table content with table context
        table_html = @rendering_context.with_child_context(:table) do |table_context|
          # Process all table rows using visitor pattern with table context
          all_rows = node.header_rows + node.body_rows
          rows_html = all_rows.map { |row| visit_with_context(row, table_context) }.join("\n")
          rows_html += "\n" unless rows_html.empty?

          %Q(<table>
#{rows_html}</table>)
        end

        %Q(<div#{id_attr} class="table">
#{caption_html}#{table_html}
</div>
)
      end

      def visit_table_row(node)
        cells_html = render_children(node)
        "<tr>#{cells_html}</tr>"
      end

      def visit_table_cell(node)
        content = render_children(node)
        tag = node.cell_type == :th ? 'th' : 'td'
        "<#{tag}>#{content}</#{tag}>"
      end

      def visit_column(node)
        # Use auto_id generated by Compiler for anchor
        id_attr = node.label ? %Q( id="#{normalize_id(node.label)}") : ''
        anchor_id = %Q(<a id="#{node.auto_id}"></a>)

        # HTMLBuilder uses h4 tag for column headers
        caption_content = render_caption_markup(node.caption_node)
        caption_html = if caption_content.empty?
                         node.label ? anchor_id : ''
                       elsif node.label
                         %Q(<h4#{id_attr}>#{anchor_id}#{caption_content}</h4>)
                       else
                         %Q(<h4>#{anchor_id}#{caption_content}</h4>)
                       end

        content = render_children(node)

        %Q(<div class="column">\n#{caption_html}#{content}</div>)
      end

      def visit_minicolumn(node)
        type = node.minicolumn_type.to_s
        id_attr = node.id ? %Q( id="#{normalize_id(node.id)}") : ''

        caption_content = render_caption_markup(node.caption_node)
        caption_html = caption_content.empty? ? '' : %Q(<p class="caption">#{caption_content}</p>\n)

        # Content already contains proper paragraph structure from ParagraphNode children
        content_html = render_children(node)

        %Q(<div class="#{type}"#{id_attr}>\n#{caption_html}#{content_html}</div>\n)
      end

      def visit_image(node)
        id_attr = node.id ? %Q( id="#{normalize_id(node.id)}") : ''

        caption_node = node.caption_node

        # Process image with caption context management
        if caption_node
          @rendering_context.with_child_context(:caption) do |caption_context|
            # Check if image is bound like HTMLBuilder does
            if @chapter&.image_bound?(node.id)
              image_image_html_with_context(node.id, caption_node, id_attr, caption_context, node.image_type)
            else
              # For dummy images, ImageNode doesn't have lines, so use empty array
              image_dummy_html_with_context(node.id, caption_node, [], id_attr, caption_context, node.image_type)
            end
          end
        elsif @chapter&.image_bound?(node.id)
          # No caption, no special context needed
          image_image_html(node.id, caption_node, id_attr, node.image_type)
        else
          image_dummy_html(node.id, caption_node, [], id_attr, node.image_type)
        end
      end

      # visit_block is now handled by Base renderer with dynamic method dispatch
      # Individual visit_block_* methods delegate to existing render_*_block methods

      def visit_block_note(node)
        render_note_block(node)
      end

      def visit_block_memo(node)
        render_memo_block(node)
      end

      def visit_block_tip(node)
        render_tip_block(node)
      end

      def visit_block_info(node)
        render_info_block(node)
      end

      def visit_block_warning(node)
        render_warning_block(node)
      end

      def visit_block_important(node)
        render_important_block(node)
      end

      def visit_block_caution(node)
        render_caution_block(node)
      end

      def visit_block_notice(node)
        render_notice_block(node)
      end

      def visit_block_quote(node)
        render_quote_block(node)
      end

      def visit_block_blockquote(node)
        render_quote_block(node)
      end

      def visit_block_lead(node)
        render_lead_block(node)
      end

      def visit_block_comment(node)
        render_comment_block(node)
      end

      def visit_block_firstlinenum(node)
        render_firstlinenum_block(node)
      end

      def visit_block_blankline(_node)
        ''
      end

      def visit_block_pagebreak(_node)
        %Q(<div class="pagebreak"></div>\n)
      end

      def visit_block_label(node)
        render_label_block(node)
      end

      def visit_block_tsize(node)
        render_tsize_block(node)
      end

      def visit_block_printendnotes(node)
        render_printendnotes_block(node)
      end

      def visit_block_flushright(node)
        render_flushright_block(node)
      end

      def visit_block_centering(node)
        render_centering_block(node)
      end

      def visit_block_bibpaper(node)
        render_bibpaper_block(node)
      end

      def visit_tex_equation(node)
        content = node.content

        math_format = config['math_format']

        return render_texequation_body(content, math_format) unless node.id?

        id_attr = %Q( id="#{normalize_id(node.id)}")
        caption_content = render_caption_markup(node.caption_node)
        caption_html = if get_chap
                         if caption_content.empty?
                           %Q(<p class="caption">#{I18n.t('equation')}#{I18n.t('format_number_header', [get_chap, @chapter.equation(node.id).number])}</p>\n)
                         else
                           %Q(<p class="caption">#{I18n.t('equation')}#{I18n.t('format_number_header', [get_chap, @chapter.equation(node.id).number])}#{I18n.t('caption_prefix')}#{caption_content}</p>\n)
                         end
                       elsif caption_content.empty?
                         %Q(<p class="caption">#{I18n.t('equation')}#{I18n.t('format_number_header_without_chapter', [@chapter.equation(node.id).number])}</p>\n)
                       else
                         %Q(<p class="caption">#{I18n.t('equation')}#{I18n.t('format_number_header_without_chapter', [@chapter.equation(node.id).number])}#{I18n.t('caption_prefix')}#{caption_content}</p>\n)
                       end

        caption_top_html = caption_top?('equation') ? caption_html : ''
        caption_bottom_html = caption_top?('equation') ? '' : caption_html

        equation_body_html = render_texequation_body(content, math_format)

        %Q(<div#{id_attr} class="caption-equation">\n#{caption_top_html}#{equation_body_html}#{caption_bottom_html}</div>\n)
      end

      # Render equation body with appropriate format (matches HTMLBuilder's texequation_body)
      def render_texequation_body(content, math_format)
        result = %Q(<div class="equation">\n)

        math_content = render_math_format(content, math_format)
        # Check if error case returned complete div (early return from helper)
        return math_content if math_content.include?('</div>')

        result + math_content + "</div>\n"
      end

      def render_math_format(content, math_format)
        case math_format
        when 'mathjax'
          # Use $$ for display mode like HTMLBuilder
          "$$#{content.gsub('<', '\lt{}').gsub('>', '\gt{}').gsub('&', '&amp;')}$$\n"
        when 'mathml'
          render_mathml_format(content)
        when 'imgmath'
          render_imgmath_format(content)
        else
          # Fallback: render as preformatted text
          %Q(<pre>#{escape(content)}\n</pre>\n)
        end
      end

      def render_mathml_format(content)
        begin
          require 'math_ml'
          require 'math_ml/symbol/character_reference'
        rescue LoadError
          app_error 'not found math_ml'
          return %Q(<div class="equation">\n<pre>#{escape(content)}\n</pre>\n</div>\n)
        end
        parser = MathML::LaTeX::Parser.new(symbol: MathML::Symbol::CharacterReference)
        # Add newline to content like HTMLBuilder does
        # parser.parse returns MathML::Math object, need to convert to string
        parser.parse(content + "\n", true).to_s
      end

      def render_imgmath_format(content)
        unless @img_math
          app_error 'ImgMath not initialized'
          return %Q(<div class="equation">\n<pre>#{escape(content)}\n</pre>\n</div>\n)
        end

        fontsize = config['imgmath_options']['fontsize'].to_f
        lineheight = config['imgmath_options']['lineheight'].to_f
        math_str = "\\begin{equation*}\n\\fontsize{#{fontsize}}{#{lineheight}}\\selectfont\n#{content}\n\\end{equation*}\n"
        key = Digest::SHA256.hexdigest(math_str)

        img_path = @img_math.defer_math_image(math_str, key)
        %Q(<img src="#{img_path}" class="math_gen_#{key}" alt="#{escape(content)}" />\n)
      end

      # Render AST to HTML body content only (without template).
      #
      # @param ast_root [Object] The root AST node to render
      # @return [String] HTML body content only
      def render_body(ast_root)
        visit(ast_root)
      end

      # Overrides Base#render to generate a complete HTML document with template.
      #
      # @return [String] Complete HTML document with template applied
      def render(ast_root)
        @body = render_body(ast_root)

        # Set up template variables like HTMLBuilder
        # Chapter title is already plain text (markup removed), just escape it
        @title = escape_content(@chapter&.title || '')
        @language = config['language'] || 'ja'
        @stylesheets = config['stylesheet'] || []
        @next = @chapter&.next_chapter
        @prev = @chapter&.prev_chapter
        @next_title = @next ? escape_content(@next.title) : ''
        @prev_title = @prev ? escape_content(@prev.title) : ''

        # Handle MathJax configuration like HTMLBuilder
        if config['math_format'] == 'mathjax'
          @javascripts.push(%Q(<script>MathJax = { tex: { inlineMath: [['\\\\(', '\\\\)']] }, svg: { fontCache: 'global' } };</script>))
          @javascripts.push(%Q(<script type="text/javascript" id="MathJax-script" async="true" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>))
        end

        # Render template
        ReVIEW::Template.load(layoutfile).result(binding)
      end

      def layoutfile
        # Determine layout file like HTMLBuilder
        if config.maker == 'webmaker'
          htmldir = 'web/html'
          localfilename = 'layout-web.html.erb'
        else
          htmldir = 'html'
          localfilename = 'layout.html.erb'
        end

        htmlfilename = if config['htmlversion'] == 5 || config['htmlversion'].nil?
                         File.join(htmldir, 'layout-html5.html.erb')
                       else
                         File.join(htmldir, 'layout-xhtml1.html.erb')
                       end

        layout_file = File.join(@book.basedir || '.', 'layouts', localfilename)

        # Check for custom layout file
        if File.exist?(layout_file)
          # Respect safe mode like HTMLBuilder
          if ENV['REVIEW_SAFE_MODE'].to_i & 4 > 0
            warn 'user\'s layout is prohibited in safe mode. ignored.'
            layout_file = File.expand_path(htmlfilename, ReVIEW::Template::TEMPLATE_DIR)
          end
        else
          # Use default template
          layout_file = File.expand_path(htmlfilename, ReVIEW::Template::TEMPLATE_DIR)
        end

        layout_file
      end

      # Helper methods for references
      def get_chap(chapter = @chapter)
        if config['secnolevel'] && config['secnolevel'] > 0 &&
           !chapter.number.nil? && !chapter.number.to_s.empty?
          if chapter.is_a?(ReVIEW::Book::Part)
            return I18n.t('part_short', chapter.number)
          else
            return chapter.format_number(nil)
          end
        end
        nil
      end

      private

      # Code block visitors using dynamic method dispatch

      def visit_code_block_emlist(node)
        lines_content = render_children(node)
        processed_content = format_code_content(lines_content, node.lang)

        code_block_wrapper(
          node,
          div_class: 'emlist-code',
          pre_class: build_pre_class('emlist', node.lang),
          content: processed_content,
          caption_style: :top_bottom
        )
      end

      def visit_code_block_emlistnum(node)
        lines_content = render_children(node)
        numbered_lines = format_emlistnum_content(lines_content, node.lang, node)

        code_block_wrapper(
          node,
          div_class: 'emlistnum-code',
          pre_class: build_pre_class('emlist', node.lang),
          content: numbered_lines,
          caption_style: :top_bottom
        )
      end

      def visit_code_block_list(node)
        lines_content = render_children(node)
        processed_content = format_code_content(lines_content, node.lang)

        code_block_wrapper(
          node,
          div_class: 'caption-code',
          pre_class: build_pre_class('list', node.lang),
          content: processed_content,
          caption_style: :numbered
        )
      end

      def visit_code_block_listnum(node)
        lines_content = render_children(node)
        numbered_lines = format_listnum_content(lines_content, node.lang, node)

        code_block_wrapper(
          node,
          div_class: 'code',
          pre_class: build_pre_class('list', node.lang, with_highlight: false),
          content: numbered_lines,
          caption_style: :numbered
        )
      end

      def visit_code_block_source(node)
        lines_content = render_children(node)
        processed_content = format_code_content(lines_content, node.lang)

        code_block_wrapper(
          node,
          div_class: 'source-code',
          pre_class: 'source',
          content: processed_content,
          caption_style: :top_bottom
        )
      end

      def visit_code_block_cmd(node)
        lines_content = render_children(node)
        processed_content = format_code_content(lines_content, node.lang)

        code_block_wrapper(
          node,
          div_class: 'cmd-code',
          pre_class: 'cmd',
          content: processed_content,
          caption_style: :top_bottom
        )
      end

      # render_fallback_code_block removed - Base renderer will raise NotImplementedError for unknown code block types

      def code_block_wrapper(node, div_class:, pre_class:, content:, caption_style:)
        id_attr = node.id ? %Q( id="#{normalize_id(node.id)}") : ''

        caption_top = render_code_caption(node, caption_style, :top)
        caption_bottom = render_code_caption(node, caption_style, :bottom)

        %Q(<div#{id_attr} class="#{div_class}">
#{caption_top}<pre class="#{pre_class}">#{content}</pre>
#{caption_bottom}</div>
)
      end

      def render_code_caption(node, style, position)
        caption_node = node.caption_node
        return '' unless caption_node

        caption_content = render_caption_markup(caption_node)
        return '' if caption_content.empty?

        case style
        when :top_bottom
          return '' unless position == :top ? caption_top?('list') : !caption_top?('list')

          %Q(<p class="caption">#{caption_content}</p>
)
        when :numbered
          return '' unless position == :top

          list_number = generate_list_header(node.id, caption_content)
          %Q(<p class="caption">#{list_number}</p>
)
        else
          ''
        end
      end

      def build_pre_class(base_class, lang, with_highlight: true)
        classes = [base_class]
        classes << "language-#{lang}" if lang
        classes << 'highlight' if with_highlight && highlight?
        classes.join(' ')
      end

      def format_code_content(lines_content, lang = nil)
        lines = lines_content.split("\n")
        body = lines.inject('') { |i, j| i + detab(j) + "\n" }

        highlight(body: body, lexer: lang, format: 'html')
      end

      def format_emlistnum_content(lines_content, lang = nil, node = nil)
        lines = lines_content.split("\n")
        lines.pop if lines.last && lines.last.empty?

        body = lines.inject('') { |i, j| i + detab(j) + "\n" }
        first_line_number = node&.first_line_num || 1

        if highlight?
          highlight(body: body, lexer: lang, format: 'html', linenum: true, options: { linenostart: first_line_number })
        else
          lines.map.with_index(first_line_number) do |line, i|
            "#{i.to_s.rjust(2)}: #{detab(line)}"
          end.join("\n") + "\n"
        end
      end

      def format_listnum_content(lines_content, lang = nil, node = nil)
        lines = lines_content.split("\n")
        lines.pop if lines.last && lines.last.empty?

        body = lines.inject('') { |i, j| i + detab(j) + "\n" }
        first_line_number = node&.first_line_num || 1

        highlighted = highlight(body: body, lexer: lang, format: 'html', linenum: true,
                                options: { linenostart: first_line_number })

        if highlight?
          highlighted
        else
          lines.map.with_index(first_line_number) do |line, i|
            "#{i.to_s.rjust(2)}: #{detab(line)}"
          end.join("\n") + "\n"
        end
      end

      def highlight?
        highlighter.highlight?('html')
      end

      def highlight(body:, lexer: nil, format: 'html', linenum: false, options: {}, location: nil)
        highlighter.highlight(
          body: body,
          lexer: lexer,
          format: format,
          linenum: linenum,
          options: options,
          location: location
        )
      end

      def highlighter
        @highlighter ||= ReVIEW::Highlighter.new(config)
      end

      def generate_list_header(id, caption)
        list_item = @chapter&.list(id)
        raise NotImplementedError, "no such list: #{id}" unless list_item

        list_num = list_item.number
        chapter_num = @chapter&.number

        if chapter_num
          "#{I18n.t('list')}#{I18n.t('format_number_header', [chapter_num, list_num])}#{I18n.t('caption_prefix')}#{caption}"
        else
          "#{I18n.t('list')}#{I18n.t('format_number_header_without_chapter', [list_num])}#{I18n.t('caption_prefix')}#{caption}"
        end
      end

      def visit_reference(node)
        if node.resolved?
          format_resolved_reference(node.resolved_data)
        else
          # Reference resolution was skipped or disabled
          # Return content as fallback
          node.content || ''
        end
      end

      # Format resolved reference based on ResolvedData
      # Uses double dispatch pattern with a dedicated formatter object
      def format_resolved_reference(data)
        data.format_with(@reference_formatter)
      end

      def visit_footnote(node)
        # Handle FootnoteNode - render as footnote or endnote definition
        # Note: This renders the footnote/endnote definition block at document level.
        # For inline footnote references (@<fn>{id}), see render_footnote method.
        footnote_content = render_children(node)

        # Check if this is a footnote or endnote based on footnote_type attribute
        if node.footnote_type == :endnote
          # Endnote - skip rendering here, will be rendered by printendnotes
          return ''
        end

        # Match HTMLBuilder's footnote output format
        footnote_number = @chapter&.footnote(node.id)&.number || '??'

        # Check epubversion for consistent output with HTMLBuilder
        if config['epubversion'].to_i == 3
          # EPUB3 version with epub:type attributes
          # Only add back link if epubmaker/back_footnote is configured (like HTMLBuilder)
          back_link = ''
          if config['epubmaker'] && config['epubmaker']['back_footnote']
            back_link = %Q(<a href="#fnb-#{normalize_id(node.id)}">#{I18n.t('html_footnote_backmark')}</a>)
          end
          %Q(<div class="footnote" epub:type="footnote" id="fn-#{normalize_id(node.id)}"><p class="footnote">#{back_link}#{I18n.t('html_footnote_textmark', footnote_number)}#{footnote_content}</p></div>)
        else
          # Non-EPUB version
          footnote_back_link = %Q(<a href="#fnb-#{normalize_id(node.id)}">*#{footnote_number}</a>)
          %Q(<div class="footnote" id="fn-#{normalize_id(node.id)}"><p class="footnote">[#{footnote_back_link}] #{footnote_content}</p></div>)
        end
      end

      def visit_embed(node)
        # Handle embed blocks and raw commands
        case node.embed_type
        when :raw, :inline
          # Process raw embed content
          process_raw_embed(node)
        else
          # Handle legacy embed blocks
          if node.arg
            # Parse target formats from argument like Builder base class
            builders = node.arg.gsub(/^\s*\|/, '').gsub(/\|\s*$/, '').gsub(/\s/, '').split(',')
            target = target_name

            # Only output if this renderer's target is in the list
            if builders.include?(target)
              content = node.lines.join("\n")
              # For HTML output, ensure XHTML compliance for self-closing tags
              content = ensure_xhtml_compliance(content)
              return content + "\n"
            else
              return ''
            end
          else
            # No format specified, output for all formats
            content = node.lines.join("\n")
            # For HTML output, ensure XHTML compliance for self-closing tags
            content = ensure_xhtml_compliance(content)
            return content + "\n"
          end
        end
      end

      def render_inline_element(type, content, node)
        # Try delegating to inline element handler first
        handler_method = "render_inline_#{type}"
        if @inline_element_handler.respond_to?(handler_method, true)
          return @inline_element_handler.send(handler_method, type, content, node)
        end

        # Fall back to renderer's own methods if handler returns nil
        method_name = "render_inline_#{type}"
        if respond_to?(method_name, true)
          send(method_name, type, content, node)
        else
          raise NotImplementedError, "Unknown inline element: #{type}"
        end
      end

      def render_note_block(node)
        render_callout_block(node, 'note')
      end

      def render_memo_block(node)
        render_callout_block(node, 'memo')
      end

      def render_tip_block(node)
        render_callout_block(node, 'tip')
      end

      def render_info_block(node)
        render_callout_block(node, 'info')
      end

      def render_warning_block(node)
        render_callout_block(node, 'warning')
      end

      def render_important_block(node)
        render_callout_block(node, 'important')
      end

      def render_caution_block(node)
        render_callout_block(node, 'caution')
      end

      def render_notice_block(node)
        render_callout_block(node, 'notice')
      end

      def render_quote_block(node)
        id_attr = node.id ? %Q( id="#{normalize_id(node.id)}") : ''
        content = render_children(node)
        %Q(<blockquote#{id_attr}>#{content}</blockquote>)
      end

      def render_lead_block(node)
        id_attr = node.id ? %Q( id="#{normalize_id(node.id)}") : ''
        content = render_children(node)
        %Q(<div#{id_attr} class="lead">\n#{content}</div>\n)
      end

      def render_comment_block(node)
        return '' unless config['draft']

        content_lines = []

        if node.args.first && !node.args.first.empty?
          content_lines << escape(node.args.first)
        end

        if node.content && !node.content.empty?
          body_content = render_children(node)
          content_lines << body_content unless body_content.empty?
        end

        return '' if content_lines.empty?

        content_str = content_lines.join('<br />')
        %Q(<div class="draft-comment">#{content_str}</div>)
      end

      def render_callout_block(node, type)
        id_attr = node.id ? %Q( id="#{normalize_id(node.id)}") : ''

        caption_content = render_caption_markup(node.caption_node)
        caption_html = caption_content.empty? ? '' : %Q(<div class="#{type}-header">#{caption_content}</div>)

        content = render_children(node)

        %Q(<div class="#{type}"#{id_attr}>\n#{caption_html}#{content}</div>)
      end

      def render_label_block(node)
        # Extract label from args
        label = node.args.first
        return '' unless label

        %Q(<a id="#{normalize_id(label)}"></a>)
      end

      def render_tsize_block(_node)
        # Table size control - HTMLBuilder outputs nothing for HTML
        # tsize is only used for LaTeX/PDF output
        ''
      end

      def render_printendnotes_block(_node)
        # Render collected endnotes like HTMLBuilder's printendnotes method
        return '' unless @chapter
        return '' unless @chapter.endnotes

        # Check if there are any endnotes using size
        return '' if @chapter.endnotes.size == 0

        # Mark that we've shown endnotes (like Builder base class)
        @shown_endnotes = true

        # Begin endnotes block
        result = %Q(<div class="endnotes">\n)

        # Render each endnote like HTMLBuilder's endnote_item
        @chapter.endnotes.each do |en|
          back = ''
          if config['epubmaker'] && config['epubmaker']['back_footnote']
            back = %Q(<a href="#endnoteb-#{normalize_id(en.id)}">#{I18n.t('html_footnote_backmark')}</a>)
          end
          # Render endnote content from footnote_node
          endnote_content = render_children(en.footnote_node)
          result += %Q(<div class="endnote" id="endnote-#{normalize_id(en.id)}"><p class="endnote">#{back}#{I18n.t('html_endnote_textmark', @chapter.endnote(en.id).number)}#{endnote_content}</p></div>\n)
        end

        # End endnotes block
        result + %Q(</div>\n)
      end

      def render_flushright_block(node)
        # Render children (which produces <p> tags)
        content = render_children(node)
        # Replace <p> with <p class="flushright"> like HTMLBuilder
        content.gsub('<p>', %Q(<p class="flushright">))
      end

      def render_centering_block(node)
        # Render children (which produces <p> tags)
        content = render_children(node)
        # Replace <p> with <p class="center"> like HTMLBuilder
        content.gsub('<p>', %Q(<p class="center">))
      end

      def render_bibpaper_block(node)
        # For BlockNode, id and caption are in args array like HTMLBuilder's bibpaper(lines, id, caption)
        id = node.args[0]
        caption_text = node.args[1]

        # Start div (puts in HTMLBuilder, so newline after)
        result = %Q(<div class="bibpaper">\n)

        # Add anchor and number like HTMLBuilder's bibpaper_header
        # bibpaper_header uses print for anchor, then puts for caption (with newline)
        if id && @chapter
          begin
            bibpaper_number = @chapter.bibpaper(id).number
            result += %Q(<a id="bib-#{normalize_id(id)}">[#{bibpaper_number}]</a> )
          rescue StandardError
            # If bibpaper not found, use ?? like other references
            result += %Q(<a id="bib-#{normalize_id(id)}">[??]</a> )
          end
        end

        # Add caption as plain text (BlockNode doesn't have caption_node)
        # HTMLBuilder uses puts " #{compile_inline(caption)}", so space before caption and newline after
        if caption_text && !caption_text.empty?
          result += escape_content(caption_text) + "\n"
        end

        # Add content wrapped in <p> if present (like split_paragraph does)
        # HTMLBuilder uses print for bibpaper_bibpaper, so no newline after
        # Then puts '</div>' adds the closing tag with newline
        content = render_children(node)
        unless content.strip.empty?
          # strip to remove paragraph newlines, match Builder's behavior
          result += %Q(<p>#{content.strip}</p>)
        end

        # Close div (puts in HTMLBuilder, so it's on the same line as </p>)
        result + "</div>\n"
      end

      def escape(str)
        # Use EscapeUtils for consistency
        escape_content(str.to_s)
      end

      def headline_prefix(level)
        return [nil, nil] unless @sec_counter

        @sec_counter.inc(level)
        anchor = @sec_counter.anchor(level)
        prefix = @sec_counter.prefix(level, config['secnolevel'])
        [prefix, anchor]
      end

      def image_image_html(id, caption_node, id_attr, image_type = :image)
        caption_html = image_header_html(id, caption_node, image_type)
        caption_present = !caption_html.empty?

        begin
          image_path = @chapter.image(id).path.sub(%r{\A\./}, '')
          alt_text = escape(render_caption_markup(caption_node))

          img_html = %Q(<img src="#{image_path}" alt="#{alt_text}" />)

          # Check caption positioning like HTMLBuilder
          if caption_top?('image') && caption_present
            %Q(<div#{id_attr} class="image">\n#{caption_html}#{img_html}\n</div>\n)
          else
            %Q(<div#{id_attr} class="image">\n#{img_html}\n#{caption_html}</div>\n)
          end
        rescue StandardError
          # If image loading fails, fall back to dummy
          image_dummy_html(id, caption_node, [], id_attr, image_type)
        end
      end

      def image_image_html_with_context(id, caption_node, id_attr, caption_context, image_type = :image)
        caption_html = image_header_html_with_context(id, caption_node, caption_context, image_type)
        caption_present = !caption_html.empty?

        begin
          image_path = @chapter.image(id).path.sub(%r{\A\./}, '')
          img_html = %Q(<img src="#{image_path}" alt="#{escape(render_caption_markup(caption_node))}" />)

          # Check caption positioning like HTMLBuilder
          if caption_top?('image') && caption_present
            %Q(<div#{id_attr} class="image">\n#{caption_html}#{img_html}\n</div>\n)
          else
            %Q(<div#{id_attr} class="image">\n#{img_html}\n#{caption_html}</div>\n)
          end
        rescue StandardError
          # If image loading fails, fall back to dummy
          image_dummy_html_with_context(id, caption_node, [], id_attr, caption_context, image_type)
        end
      end

      def image_dummy_html(id, caption_node, lines, id_attr, image_type = :image)
        caption_html = image_header_html(id, caption_node, image_type)
        caption_present = !caption_html.empty?

        # Generate dummy image content exactly like HTMLBuilder
        # HTMLBuilder puts each line and adds newlines via 'puts'
        lines_content = if lines.empty?
                          "\n" # Empty image block just has one newline
                        else
                          "\n" + lines.map { |line| escape(line) }.join("\n") + "\n"
                        end

        # Check caption positioning like HTMLBuilder
        if caption_top?('image') && caption_present
          %Q(<div#{id_attr} class="image">\n#{caption_html}<pre class="dummyimage">#{lines_content}</pre>\n</div>\n)
        else
          %Q(<div#{id_attr} class="image">\n<pre class="dummyimage">#{lines_content}</pre>\n#{caption_html}</div>\n)
        end
      end

      def image_dummy_html_with_context(id, caption_node, lines, id_attr, caption_context, image_type = :image)
        caption_html = image_header_html_with_context(id, caption_node, caption_context, image_type)
        caption_present = !caption_html.empty?

        # Generate dummy image content exactly like HTMLBuilder
        lines_content = if lines.empty?
                          "\n" # Empty image block just has one newline
                        else
                          "\n" + lines.map { |line| escape(line) }.join("\n") + "\n"
                        end

        # Check caption positioning like HTMLBuilder
        if caption_top?('image') && caption_present
          %Q(<div#{id_attr} class="image">\n#{caption_html}<pre class="dummyimage">#{lines_content}</pre>\n</div>\n)
        else
          %Q(<div#{id_attr} class="image">\n<pre class="dummyimage">#{lines_content}</pre>\n#{caption_html}</div>\n)
        end
      end

      def image_header_html(id, caption_node, image_type = :image)
        caption_content = render_caption_markup(caption_node)
        return '' if caption_content.empty?

        # For indepimage (numberless image), use numberless_image label like HTMLBuilder
        if image_type == :indepimage || image_type == :numberlessimage
          image_number = I18n.t('numberless_image')
        else
          # Generate image number like HTMLBuilder using chapter image index
          image_item = @chapter&.image(id)
          unless image_item && image_item.number
            raise ReVIEW::KeyError, "image '#{id}' not found"
          end

          image_number = if get_chap
                           %Q(#{I18n.t('image')}#{I18n.t('format_number_header', [get_chap, image_item.number])})
                         else
                           %Q(#{I18n.t('image')}#{I18n.t('format_number_header_without_chapter', [image_item.number])})
                         end
        end

        %Q(<p class="caption">\n#{image_number}#{I18n.t('caption_prefix')}#{caption_content}\n</p>\n)
      end

      def image_header_html_with_context(id, caption_node, caption_context, image_type = :image)
        caption_content = render_caption_with_context(caption_node, caption_context)
        return '' if caption_content.empty?

        # For indepimage (numberless image), use numberless_image label like HTMLBuilder
        if image_type == :indepimage || image_type == :numberlessimage
          image_number = I18n.t('numberless_image')
        else
          # Generate image number like HTMLBuilder using chapter image index
          image_item = @chapter&.image(id)
          unless image_item && image_item.number
            raise ReVIEW::KeyError, "image '#{id}' not found"
          end

          image_number = if get_chap
                           %Q(#{I18n.t('image')}#{I18n.t('format_number_header', [get_chap, image_item.number])})
                         else
                           %Q(#{I18n.t('image')}#{I18n.t('format_number_header_without_chapter', [image_item.number])})
                         end
        end

        %Q(<p class="caption">\n#{image_number}#{I18n.t('caption_prefix')}#{caption_content}\n</p>\n)
      end

      def generate_table_header(id, caption)
        table_item = @chapter.table(id)
        table_num = table_item.number
        chapter_num = @chapter.number

        if chapter_num
          "#{I18n.t('table')}#{I18n.t('format_number_header', [chapter_num, table_num])}#{I18n.t('caption_prefix')}#{caption}"
        else
          "#{I18n.t('table')}#{I18n.t('format_number_header_without_chapter', [table_num])}#{I18n.t('caption_prefix')}#{caption}"
        end
      rescue ReVIEW::KeyError
        raise NotImplementedError, "no such table: #{id}"
      end

      def render_imgtable(node)
        id = node.id
        caption_node = node.caption_node

        # Check if image is bound like HTMLBuilder does
        unless @chapter&.image_bound?(id)
          warn "image not bound: #{id}"
          # For dummy images, use empty array for lines (no lines in TableNode)
          return render_imgtable_dummy(id, caption_node, [])
        end

        id_attr = id ? %Q( id="#{normalize_id(id)}") : ''

        # Generate table caption HTML if caption exists
        caption_content = render_caption_markup(caption_node)
        caption_html = if caption_content.empty?
                         ''
                       else
                         table_caption = generate_table_header(id, caption_content)
                         %Q(<p class="caption">#{table_caption}</p>\n)
                       end

        # Render image tag
        begin
          image_path = @chapter.image(id).path.sub(%r{\A\./}, '')
          alt_text = escape(caption_plain_text(caption_node))
          img_html = %Q(<img src="#{image_path}" alt="#{alt_text}" />\n)

          # Check caption positioning like HTMLBuilder (uses 'table' type for imgtable)
          if caption_top?('table') && !caption_content.empty?
            %Q(<div#{id_attr} class="imgtable image">\n#{caption_html}#{img_html}</div>\n)
          else
            %Q(<div#{id_attr} class="imgtable image">\n#{img_html}#{caption_html}</div>\n)
          end
        rescue ReVIEW::KeyError
          app_error "no such table: #{id}"
        end
      end

      def render_imgtable_dummy(id, caption_node, lines)
        id_attr = id ? %Q( id="#{normalize_id(id)}") : ''

        # Generate table caption HTML if caption exists
        caption_content = render_caption_markup(caption_node)
        caption_html = if caption_content.empty?
                         ''
                       else
                         table_caption = generate_table_header(id, caption_content)
                         %Q(<p class="caption">#{table_caption}</p>\n)
                       end

        # Generate dummy content like image_dummy_html
        lines_content = if lines.empty?
                          "\n"
                        else
                          "\n" + lines.map { |line| escape(line) }.join("\n") + "\n"
                        end

        # Check caption positioning like HTMLBuilder
        if caption_top?('table') && !caption_content.empty?
          %Q(<div#{id_attr} class="imgtable image">\n#{caption_html}<pre class="dummyimage">#{lines_content}</pre>\n</div>\n)
        else
          %Q(<div#{id_attr} class="imgtable image">\n<pre class="dummyimage">#{lines_content}</pre>\n#{caption_html}</div>\n)
        end
      end

      def render_caption_markup(caption_node)
        return '' unless caption_node

        content = render_children(caption_node)
        # Join lines like visit_paragraph does
        join_paragraph_lines(content)
      end

      def render_caption_with_context(caption_node, caption_context)
        return '' unless caption_node

        render_children_with_context(caption_node, caption_context)
      end

      def caption_plain_text(caption_node)
        caption_node&.to_text.to_s
      end

      # Process raw embed content (//raw and @<raw>)
      def process_raw_embed(node)
        # Check if content should be output for this renderer
        return '' unless node.targeted_for?('html')

        # Get processed content and convert \\n to actual newlines
        content = node.content || ''
        processed_content = content.gsub('\\n', "\n")

        # Apply XHTML compliance for HTML output
        ensure_xhtml_compliance(processed_content)
      end

      def ensure_xhtml_compliance(content)
        content.gsub(/<hr(\s[^>]*)?>/, '<hr\1 />').
          gsub(/<br(\s[^>]*)?>/, '<br\1 />').
          gsub(%r{<img([^>]*[^/])>}, '<img\1 />').
          gsub(%r{<input([^>]*[^/])>}, '<input\1 />')
      end

      # Builder compatibility - return target name for embed blocks
      def target_name
        'html'
      end

      def render_children_with_context(node, context)
        old_context = @rendering_context
        @rendering_context = context
        result = render_children(node)
        @rendering_context = old_context
        result
      end

      def visit_with_context(node, context)
        old_context = @rendering_context
        @rendering_context = context
        result = visit(node)
        @rendering_context = old_context
        result
      end
    end
  end
end
