# frozen_string_literal: true

# Copyright (c) 2024 Minero Aoki, Kenshi Muto
#
# This program is free software.
# You can distribute or modify this program under the terms of
# the GNU LGPL, Lesser General Public License version 2.1.

require 'review/renderer/base'
require 'review/ast/caption_node'
require 'review/renderer/rendering_context'
require 'review/htmlutils'
require 'review/textutils'
require 'review/escape_utils'
require 'review/highlighter'
require 'review/sec_counter'
require 'review/i18n'
require 'review/loggable'
require 'review/ast/indexer'
require 'review/ast/compiler'
require 'review/template'

module ReVIEW
  module Renderer
    class HtmlRenderer < Base # rubocop:disable Metrics/ClassLength
      include ReVIEW::HTMLUtils
      include ReVIEW::TextUtils
      include ReVIEW::EscapeUtils
      include ReVIEW::Loggable

      attr_reader :chapter, :book

      def initialize(chapter)
        super

        # Initialize logger like HTMLBuilder for error handling
        @logger = ReVIEW.logger

        # Initialize section counter like HTMLBuilder (handle nil chapter)
        @sec_counter = @chapter ? SecCounter.new(5, @chapter) : nil

        # Flag to track if indexes have been generated using AST::Indexer
        @ast_indexes_generated = false

        # Initialize template variables like HTMLBuilder
        @javascripts = []
        @body_ext = ''

        # Initialize RenderingContext for cleaner state management
        @rendering_context = RenderingContext.new(:document)
      end

      def visit_document(node)
        generate_ast_indexes(node)
        render_children(node)
      end

      def visit_headline(node)
        level = node.level
        caption = render_caption_markup(node.caption_node)

        if node.nonum? || node.notoc? || node.nodisp?
          # Use label if provided, otherwise use auto_id generated by Compiler
          id = normalize_id(node.label || node.auto_id)

          spacing_before = level > 1 ? "\n" : ''

          if node.nodisp?
            a_tag = %Q(<a id="#{id}" />)
            %Q(#{spacing_before}#{a_tag}<h#{level} id="#{id}" hidden="true">#{caption}</h#{level}>\n)
          elsif node.notoc?
            %Q(#{spacing_before}<h#{level} id="#{id}" notoc="true">#{caption}</h#{level}>\n)
          else
            %Q(#{spacing_before}<h#{level} id="#{id}">#{caption}</h#{level}>\n)
          end
        else
          prefix, anchor = headline_prefix(level)

          anchor_html = anchor ? %Q(<a id="h#{anchor}"></a>) : ''
          secno_html = prefix ? %Q(<span class="secno">#{prefix}</span>) : ''
          spacing_before = level > 1 ? "\n" : ''

          if node.label
            label_id = normalize_id(node.label)
            %Q(#{spacing_before}<h#{level} id="#{label_id}">#{anchor_html}#{secno_html}#{caption}</h#{level}>\n)
          else
            "#{spacing_before}<h#{level}>#{anchor_html}#{secno_html}#{caption}</h#{level}>\n"
          end
        end
      end

      def visit_paragraph(node)
        content = render_children(node)
        content = join_paragraph_lines(content).strip

        # Check for noindent attribute
        if node.attribute?(:noindent)
          %Q(<p class="noindent">#{content}</p>\n)
        else
          "<p>#{content}</p>\n"
        end
      end

      # Join paragraph lines according to join_lines_by_lang setting
      # This matches HTMLBuilder's join_lines_to_paragraph behavior
      #
      # @param content [String] paragraph content with newlines
      # @return [String] processed content with lines joined appropriately
      def join_paragraph_lines(content)
        if @book.config['join_lines_by_lang']
          # Split by newlines to get individual lines
          lines = content.split("\n")

          # Add spaces between lines based on language rules
          lazy = true
          lang = @book.config['language'] || 'ja'
          0.upto(lines.size - 2) do |n|
            if add_space?(lines[n], lines[n + 1], lang, lazy)
              lines[n] += ' '
            end
          end
          lines.join
        else
          # Default: just remove newlines (no space added)
          content.gsub(/\n+/, '')
        end
      end

      def visit_list(node)
        tag = case node.list_type
              when :ul
                'ul'
              when :ol
                'ol'
              when :dl
                'dl'
              else
                raise NotImplementedError, "HTMLRenderer does not support list_type #{node.list_type}."
              end

        # Check for start_number for ordered lists
        # Only output start attribute if it's not the default value (1)
        start_attr = ''
        if node.list_type == :ol && node.start_number && node.start_number != 1
          start_attr = %Q( start="#{node.start_number}")
        end

        content = render_children(node)
        # Format list items with proper line breaks like HTMLBuilder
        formatted_content = content.gsub(%r{</li>(?=<li>)}, "</li>\n")
        formatted_content = formatted_content.gsub(/<li>([^<]*)<ul>/, "<li>\\1<ul>\n")
        formatted_content = formatted_content.gsub('</ul></li>', "</ul>\n</li>")
        "<#{tag}#{start_attr}>\n#{formatted_content}\n</#{tag}>\n"
      end

      def visit_list_item(node)
        # Get parent list to determine list type
        parent_list = node.parent
        if parent_list && parent_list.list_type == :dl
          # Definition list item - use term_children for term like LaTeXRenderer
          term = if node.term_children&.any?
                   node.term_children.map { |child| visit(child) }.join
                 else
                   ''
                 end

          # Children contain the definition content
          # Join all children into a single dd like HTMLBuilder does with join_lines_to_paragraph
          if node.children.empty?
            # Only term, no definition - add empty dd like HTMLBuilder
            "<dt>#{term}</dt><dd></dd>"
          else
            # Render all child content and join together
            definition_parts = node.children.map { |child| visit(child) }
            # Join multiple paragraphs/text into single dd content, removing <p> tags
            definition_content = definition_parts.map { |part| part.gsub(%r{</?p[^>]*>}, '').strip }.join
            "<dt>#{term}</dt><dd>#{definition_content}</dd>"
          end
        else
          # Regular list item
          content = render_children(node)
          "<li>#{content}</li>"
        end
      end

      def visit_text(node)
        escape_content(node.content.to_s)
      end

      def visit_inline(node)
        content = render_children(node)
        render_inline_element(node.inline_type, content, node)
      end

      # visit_code_block is now handled by Base renderer with dynamic method dispatch

      def visit_code_line(node)
        # Process each line like HTMLBuilder - detab and preserve exact content
        # Add newline like other renderers (LaTeX, Markdown, Top) do
        line_content = render_children(node)
        detab(line_content) + "\n"
      end

      def visit_table(node)
        # Check if this is an imgtable - handle as image like HTMLBuilder
        if node.table_type == :imgtable
          return render_imgtable(node)
        end

        id_attr = node.id ? %Q( id="#{normalize_id(node.id)}") : ''

        # Process caption with proper context management
        caption_html = if node.caption_node
                         @rendering_context.with_child_context(:caption) do |caption_context|
                           caption_content = render_caption_with_context(node.caption_node, caption_context)
                           # Generate table number like HTMLBuilder using chapter table index
                           table_number = if node.id
                                            generate_table_header(node.id, caption_content)
                                          else
                                            # No ID - just use caption without numbering
                                            caption_content
                                          end
                           %Q(<p class="caption">#{table_number}</p>
)
                         end
                       else
                         ''
                       end

        # Process table content with table context
        table_html = @rendering_context.with_child_context(:table) do |table_context|
          # Process all table rows using visitor pattern with table context
          all_rows = node.header_rows + node.body_rows
          rows_html = all_rows.map { |row| visit_with_context(row, table_context) }.join("\n")
          rows_html += "\n" unless rows_html.empty?

          %Q(<table>
#{rows_html}</table>)
        end

        %Q(<div#{id_attr} class="table">
#{caption_html}#{table_html}
</div>
)
      end

      def visit_table_row(node)
        cells_html = render_children(node)
        "<tr>#{cells_html}</tr>"
      end

      def visit_table_cell(node)
        content = render_children(node)
        tag = node.cell_type == :th ? 'th' : 'td'
        "<#{tag}>#{content}</#{tag}>"
      end

      def visit_column(node)
        # Use auto_id generated by Compiler for anchor
        id_attr = node.label ? %Q( id="#{normalize_id(node.label)}") : ''
        anchor_id = %Q(<a id="#{node.auto_id}"></a>)

        # HTMLBuilder uses h4 tag for column headers
        caption_content = render_caption_markup(node.caption_node)
        caption_html = if caption_content.empty?
                         node.label ? anchor_id : ''
                       elsif node.label
                         %Q(<h4#{id_attr}>#{anchor_id}#{caption_content}</h4>)
                       else
                         %Q(<h4>#{anchor_id}#{caption_content}</h4>)
                       end

        content = render_children(node)

        %Q(<div class="column">\n#{caption_html}#{content}</div>)
      end

      def visit_minicolumn(node)
        type = node.minicolumn_type.to_s
        id_attr = node.id ? %Q( id="#{normalize_id(node.id)}") : ''

        caption_content = render_caption_markup(node.caption_node)
        caption_html = caption_content.empty? ? '' : %Q(<p class="caption">#{caption_content}</p>\n)

        # Content already contains proper paragraph structure from ParagraphNode children
        content_html = render_children(node)

        %Q(<div class="#{type}"#{id_attr}>\n#{caption_html}#{content_html}</div>\n)
      end

      def visit_image(node)
        id_attr = node.id ? %Q( id="#{normalize_id(node.id)}") : ''

        caption_node = node.caption_node

        # Process image with caption context management
        if caption_node
          @rendering_context.with_child_context(:caption) do |caption_context|
            # Check if image is bound like HTMLBuilder does
            if @chapter&.image_bound?(node.id)
              image_image_html_with_context(node.id, caption_node, id_attr, caption_context, node.image_type)
            else
              # For dummy images, ImageNode doesn't have lines, so use empty array
              image_dummy_html_with_context(node.id, caption_node, [], id_attr, caption_context, node.image_type)
            end
          end
        elsif @chapter&.image_bound?(node.id)
          # No caption, no special context needed
          image_image_html(node.id, caption_node, id_attr, node.image_type)
        else
          image_dummy_html(node.id, caption_node, [], id_attr, node.image_type)
        end
      end

      # visit_block is now handled by Base renderer with dynamic method dispatch
      # Individual visit_block_* methods delegate to existing render_*_block methods

      def visit_block_note(node)
        render_note_block(node)
      end

      def visit_block_memo(node)
        render_memo_block(node)
      end

      def visit_block_tip(node)
        render_tip_block(node)
      end

      def visit_block_info(node)
        render_info_block(node)
      end

      def visit_block_warning(node)
        render_warning_block(node)
      end

      def visit_block_important(node)
        render_important_block(node)
      end

      def visit_block_caution(node)
        render_caution_block(node)
      end

      def visit_block_notice(node)
        render_notice_block(node)
      end

      def visit_block_quote(node)
        render_quote_block(node)
      end

      def visit_block_blockquote(node)
        render_quote_block(node)
      end

      def visit_block_lead(node)
        render_lead_block(node)
      end

      def visit_block_comment(node)
        render_comment_block(node)
      end

      def visit_block_firstlinenum(node)
        render_firstlinenum_block(node)
      end

      def visit_block_blankline(_node)
        ''
      end

      def visit_block_pagebreak(_node)
        %Q(<div class="pagebreak"></div>\n)
      end

      def visit_block_label(node)
        render_label_block(node)
      end

      def visit_block_tsize(node)
        render_tsize_block(node)
      end

      def visit_block_printendnotes(node)
        render_printendnotes_block(node)
      end

      def visit_block_flushright(node)
        render_flushright_block(node)
      end

      def visit_block_centering(node)
        render_centering_block(node)
      end

      def visit_block_bibpaper(node)
        render_bibpaper_block(node)
      end

      def visit_tex_equation(node)
        content = node.content

        math_format = config['math_format']

        return render_texequation_body(content, math_format) unless node.id?

        id_attr = %Q( id="#{normalize_id(node.id)}")
        caption_content = render_caption_markup(node.caption_node)
        caption_html = if get_chap
                         if caption_content.empty?
                           %Q(<p class="caption">#{I18n.t('equation')}#{I18n.t('format_number_header', [get_chap, @chapter.equation(node.id).number])}</p>\n)
                         else
                           %Q(<p class="caption">#{I18n.t('equation')}#{I18n.t('format_number_header', [get_chap, @chapter.equation(node.id).number])}#{I18n.t('caption_prefix')}#{caption_content}</p>\n)
                         end
                       elsif caption_content.empty?
                         %Q(<p class="caption">#{I18n.t('equation')}#{I18n.t('format_number_header_without_chapter', [@chapter.equation(node.id).number])}</p>\n)
                       else
                         %Q(<p class="caption">#{I18n.t('equation')}#{I18n.t('format_number_header_without_chapter', [@chapter.equation(node.id).number])}#{I18n.t('caption_prefix')}#{caption_content}</p>\n)
                       end

        caption_top_html = caption_top?('equation') ? caption_html : ''
        caption_bottom_html = caption_top?('equation') ? '' : caption_html

        equation_body_html = render_texequation_body(content, math_format)

        %Q(<div#{id_attr} class="caption-equation">\n#{caption_top_html}#{equation_body_html}#{caption_bottom_html}</div>\n)
      end

      # Render equation body with appropriate format (matches HTMLBuilder's texequation_body)
      def render_texequation_body(content, math_format)
        result = %Q(<div class="equation">\n)

        result += case math_format
                  when 'mathjax'
                    # Use $$ for display mode like HTMLBuilder
                    "$$#{content.gsub('<', '\lt{}').gsub('>', '\gt{}').gsub('&', '&amp;')}$$\n"
                  when 'mathml'
                    # TODO: MathML support would require math_ml gem
                    # For now, fallback to plain text
                    %Q(<pre>#{escape(content)}\n</pre>\n)
                  when 'imgmath' # rubocop:disable Lint/DuplicateBranch
                    # TODO: Image-based math would require imgmath support
                    # For now, fallback to plain text
                    %Q(<pre>#{escape(content)}\n</pre>\n)
                  else # rubocop:disable Lint/DuplicateBranch
                    # Fallback: render as preformatted text
                    %Q(<pre>#{escape(content)}\n</pre>\n)
                  end

        result + "</div>\n"
      end

      # Get equation number for texequation blocks
      def get_equation_number(equation_id)
        if @chapter && @chapter.equation_index
          begin
            equation_number = @chapter.equation_index.number(equation_id)
            if @chapter.number
              "#{@chapter.number}.#{equation_number}"
            else
              equation_number.to_s
            end
          rescue StandardError
            # Fallback if equation not found in index
            '??'
          end
        else
          '??'
        end
      end

      # Render AST to HTML body content only (without template).
      # This method is useful for testing and comparison purposes.
      #
      # @param ast_root [Object] The root AST node to render
      # @return [String] HTML body content only
      def render_body(ast_root)
        visit(ast_root)
      end

      # Overrides Base#render to generate a complete HTML document with template.
      #
      # @return [String] Complete HTML document with template applied
      def render(ast_root)
        @body = render_body(ast_root)

        # Set up template variables like HTMLBuilder
        # Chapter title is already plain text (markup removed), just escape it
        @title = escape_content(@chapter&.title || '')
        @language = config['language'] || 'ja'
        @stylesheets = config['stylesheet'] || []
        @next = @chapter&.next_chapter
        @prev = @chapter&.prev_chapter
        @next_title = @next ? escape_content(@next.title) : ''
        @prev_title = @prev ? escape_content(@prev.title) : ''

        # Handle MathJax configuration like HTMLBuilder
        if config['math_format'] == 'mathjax'
          @javascripts.push(%Q(<script>MathJax = { tex: { inlineMath: [['\\\\(', '\\\\)']] }, svg: { fontCache: 'global' } };</script>))
          @javascripts.push(%Q(<script type="text/javascript" id="MathJax-script" async="true" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>))
        end

        # Render template
        ReVIEW::Template.load(layoutfile).result(binding)
      end

      def layoutfile
        # Determine layout file like HTMLBuilder
        if config.maker == 'webmaker'
          htmldir = 'web/html'
          localfilename = 'layout-web.html.erb'
        else
          htmldir = 'html'
          localfilename = 'layout.html.erb'
        end

        htmlfilename = if config['htmlversion'] == 5 || config['htmlversion'].nil?
                         File.join(htmldir, 'layout-html5.html.erb')
                       else
                         File.join(htmldir, 'layout-xhtml1.html.erb')
                       end

        layout_file = File.join(@book&.basedir || '.', 'layouts', localfilename)

        # Check for custom layout file
        if File.exist?(layout_file)
          # Respect safe mode like HTMLBuilder
          if ENV['REVIEW_SAFE_MODE'].to_i & 4 > 0
            warn 'user\'s layout is prohibited in safe mode. ignored.'
            layout_file = File.expand_path(htmlfilename, ReVIEW::Template::TEMPLATE_DIR)
          end
        else
          # Use default template
          layout_file = File.expand_path(htmlfilename, ReVIEW::Template::TEMPLATE_DIR)
        end

        layout_file
      end

      # Render footnote content (must be protected for InlineElementRenderer access)
      # This method is called with explicit receiver from InlineElementRenderer
      def render_footnote_content(footnote_node)
        render_children(footnote_node)
      end

      # Public methods for inline element rendering
      # These methods need to be accessible from InlineElementRenderer

      def render_list(content, _node)
        # Generate proper list reference exactly like HTMLBuilder's inline_list method
        list_id = content

        begin
          # Use exactly the same logic as HTMLBuilder's inline_list method
          chapter, extracted_id = extract_chapter_id(list_id)

          # Generate list number using the same pattern as Builder base class
          list_number = if get_chap(chapter)
                          %Q(#{I18n.t('list')}#{I18n.t('format_number', [get_chap(chapter), chapter.list(extracted_id).number])})
                        else
                          %Q(#{I18n.t('list')}#{I18n.t('format_number_without_chapter', [chapter.list(extracted_id).number])})
                        end

          # Generate href exactly like HTMLBuilder with chapterlink check
          if config['chapterlink']
            %Q(<span class="listref"><a href="./#{chapter.id}#{extname}##{normalize_id(extracted_id)}">#{list_number}</a></span>)
          else
            %Q(<span class="listref">#{list_number}</span>)
          end
        rescue ReVIEW::KeyError
          # Use app_error for consistency with HTMLBuilder error handling
          app_error("unknown list: #{list_id}")
        end
      end

      def render_img(content, _node)
        # Generate proper image reference exactly like HTMLBuilder's inline_img method
        img_id = content

        begin
          # Use exactly the same logic as HTMLBuilder's inline_img method
          chapter, extracted_id = extract_chapter_id(img_id)

          # Generate image number using the same pattern as Builder base class
          image_number = if get_chap(chapter)
                           %Q(#{I18n.t('image')}#{I18n.t('format_number', [get_chap(chapter), chapter.image(extracted_id).number])})
                         else
                           %Q(#{I18n.t('image')}#{I18n.t('format_number_without_chapter', [chapter.image(extracted_id).number])})
                         end

          # Generate href exactly like HTMLBuilder with chapterlink check
          if config['chapterlink']
            %Q(<span class="imgref"><a href="./#{chapter.id}#{extname}##{normalize_id(extracted_id)}">#{image_number}</a></span>)
          else
            %Q(<span class="imgref">#{image_number}</span>)
          end
        rescue ReVIEW::KeyError
          # Use app_error for consistency with HTMLBuilder error handling
          app_error("unknown image: #{img_id}")
        end
      end

      def render_inline_b(_type, content, _node)
        %Q(<b>#{content}</b>)
      end

      def render_inline_strong(_type, content, _node)
        %Q(<strong>#{content}</strong>)
      end

      def render_inline_i(_type, content, _node)
        %Q(<i>#{content}</i>)
      end

      def render_inline_em(_type, content, _node)
        %Q(<em>#{content}</em>)
      end

      def render_inline_code(_type, content, _node)
        %Q(<code class="inline-code tt">#{content}</code>)
      end

      def render_inline_tt(_type, content, _node)
        %Q(<code class="tt">#{content}</code>)
      end

      def render_inline_ttb(_type, content, _node)
        %Q(<code class="tt"><b>#{content}</b></code>)
      end

      def render_inline_tti(_type, content, _node)
        %Q(<code class="tt"><i>#{content}</i></code>)
      end

      def render_inline_kbd(_type, content, _node)
        %Q(<kbd>#{content}</kbd>)
      end

      def render_inline_samp(_type, content, _node)
        %Q(<samp>#{content}</samp>)
      end

      def render_inline_var(_type, content, _node)
        %Q(<var>#{content}</var>)
      end

      def render_inline_sup(_type, content, _node)
        %Q(<sup>#{content}</sup>)
      end

      def render_inline_sub(_type, content, _node)
        %Q(<sub>#{content}</sub>)
      end

      def render_inline_del(_type, content, _node)
        %Q(<del>#{content}</del>)
      end

      def render_inline_ins(_type, content, _node)
        %Q(<ins>#{content}</ins>)
      end

      def render_inline_u(_type, content, _node)
        %Q(<u>#{content}</u>)
      end

      def render_inline_br(_type, _content, _node)
        '<br />'
      end

      def render_inline_raw(_type, content, node)
        if node.args.first
          format = node.args.first
          if format == 'html'
            content
          else
            '' # Ignore raw content for other formats
          end
        else
          content
        end
      end

      def render_inline_embed(_type, content, node)
        # @<embed> simply outputs its content as-is, like Builder's inline_embed
        # It can optionally specify target formats like @<embed>{|html,latex|content}
        if node.args.first
          args = node.args.first
          # DEBUG
          if ENV['REVIEW_DEBUG']
            puts "DEBUG render_inline_embed: content=#{content.inspect}, args=#{args.inspect}"
          end
          if matched = args.match(/\|(.*?)\|(.*)/)
            builders = matched[1].split(',').map { |i| i.gsub(/\s/, '') }
            if builders.include?('html')
              matched[2]
            else
              ''
            end
          else
            args
          end
        else
          content
        end
      end

      def render_inline_chap(_type, _content, node)
        id = node.reference_id
        begin
          chapter_num = @book.chapter_index.number(id)
          if config['chapterlink']
            %Q(<a href="./#{id}#{extname}">#{chapter_num}</a>)
          else
            chapter_num
          end
        rescue ReVIEW::KeyError
          app_error "unknown chapter: #{id}"
        end
      end

      def render_inline_title(_type, _content, node)
        id = node.reference_id
        begin
          # Find the chapter and get its title
          chapter = find_chapter_by_id(id)
          raise ReVIEW::KeyError unless chapter

          # Chapter title is already plain text (markup removed), just escape it
          title = escape_content(chapter.title)
          if config['chapterlink']
            %Q(<a href="./#{id}#{extname}">#{title}</a>)
          else
            title
          end
        rescue ReVIEW::KeyError
          app_error "unknown chapter: #{id}"
        end
      end

      def render_inline_chapref(_type, _content, node)
        id = node.reference_id
        begin
          # Use display_string like Builder to get chapter number + title
          # This returns formatted string like "第1章「タイトル」" from I18n.t('chapter_quote')
          display_str = @book.chapter_index.display_string(id)
          if config['chapterlink']
            %Q(<a href="./#{id}#{extname}">#{display_str}</a>)
          else
            display_str
          end
        rescue ReVIEW::KeyError
          app_error "unknown chapter: #{id}"
        end
      end

      def render_inline_list(_type, _content, node)
        id = node.reference_id
        self.render_list(id, node)
      end

      def render_inline_img(_type, _content, node)
        id = node.reference_id
        self.render_img(id, node)
      end

      def render_inline_table(_type, _content, node)
        id = node.reference_id
        self.render_table(id, node)
      end

      def render_inline_fn(_type, content, node)
        fn_id = node.reference_id
        if fn_id
          # Get footnote number from chapter like HTMLBuilder
          begin
            fn_number = @chapter.footnote(fn_id).number
            # Check epubversion for consistent output with HTMLBuilder
            if @book.config['epubversion'].to_i == 3
              %Q(<a id="fnb-#{normalize_id(fn_id)}" href="#fn-#{normalize_id(fn_id)}" class="noteref" epub:type="noteref">#{I18n.t('html_footnote_refmark', fn_number)}</a>)
            else
              %Q(<a id="fnb-#{normalize_id(fn_id)}" href="#fn-#{normalize_id(fn_id)}" class="noteref">*#{fn_number}</a>)
            end
          rescue ReVIEW::KeyError
            # Fallback if footnote not found
            content
          end
        else
          content
        end
      end

      def render_inline_kw(_type, content, node)
        if node.args.length >= 2
          word = escape_content(node.args[0])
          alt = escape_content(node.args[1].strip)
          # Format like HTMLBuilder: word + space + parentheses with alt inside <b> tag
          text = "#{word} (#{alt})"
          # IDX comment uses only the word, like HTMLBuilder
          %Q(<b class="kw">#{text}</b><!-- IDX:#{word} -->)
        else
          # content is already escaped, use node.args.first for IDX comment
          index_term = node.args.first || content
          %Q(<b class="kw">#{content}</b><!-- IDX:#{escape_content(index_term)} -->)
        end
      end

      def render_inline_bou(_type, content, _node)
        %Q(<span class="bou">#{content}</span>)
      end

      def render_inline_ami(_type, content, _node)
        %Q(<span class="ami">#{content}</span>)
      end

      def render_inline_href(_type, content, node)
        args = node.args || []
        if args.length >= 2
          # Get raw URL and text from args, escape them
          url = escape_content(args[0])
          text = escape_content(args[1])
          # Handle internal references (URLs starting with #)
          if args[0].start_with?('#')
            anchor = args[0].sub(/\A#/, '')
            %Q(<a href="##{escape_content(anchor)}" class="link">#{text}</a>)
          else
            %Q(<a href="#{url}" class="link">#{text}</a>)
          end
        elsif node.args.first
          # Single argument case - use raw arg for URL
          url = escape_content(node.args.first)
          if node.args.first.start_with?('#')
            anchor = node.args.first.sub(/\A#/, '')
            %Q(<a href="##{escape_content(anchor)}" class="link">#{content}</a>)
          else
            %Q(<a href="#{url}" class="link">#{content}</a>)
          end
        else
          # Fallback: content is already escaped
          %Q(<a href="#{content}" class="link">#{content}</a>)
        end
      end

      def render_inline_ruby(_type, content, node)
        if node.args.length >= 2
          base = node.args[0]
          ruby = node.args[1]
          %Q(<ruby>#{escape_content(base)}<rt>#{escape_content(ruby)}</rt></ruby>)
        else
          content
        end
      end

      def render_inline_m(_type, content, _node)
        # Use 'equation' class like HTMLBuilder
        %Q(<span class="equation">#{content}</span>)
      end

      def render_inline_idx(_type, content, node)
        # Use HTML comment format like HTMLBuilder
        # content is already escaped for display
        index_str = node.args.first || content
        %Q(#{content}<!-- IDX:#{escape_comment(index_str)} -->)
      end

      def render_inline_hidx(_type, _content, node)
        # Use HTML comment format like HTMLBuilder
        # hidx doesn't display content, only outputs the index comment
        index_str = node.args.first || ''
        %Q(<!-- IDX:#{escape_comment(index_str)} -->)
      end

      def render_inline_comment(_type, content, _node)
        if config['draft']
          %Q(<span class="draft-comment">#{content}</span>)
        else
          ''
        end
      end

      def render_inline_sec(_type, _content, node)
        # Section number reference: @<sec>{id} or @<sec>{chapter|id}
        # This should match HTMLBuilder's inline_sec behavior
        id = node.reference_id
        begin
          chap, id2 = extract_chapter_id(id)
          n = chap.headline_index.number(id2)

          # Get section number like Builder does
          section_number = if n.present? && chap.number && over_secnolevel?(n, chap)
                             n
                           else
                             ''
                           end

          if config['chapterlink']
            anchor = 'h' + n.tr('.', '-')
            %Q(<a href="#{chap.id}#{extname}##{anchor}">#{section_number}</a>)
          else
            section_number
          end
        rescue ReVIEW::KeyError
          app_error "unknown headline: #{id}"
        end
      end

      def render_inline_secref(type, content, node)
        render_inline_hd(type, content, node)
      end

      def render_inline_labelref(_type, content, node)
        # Label reference: @<labelref>{id}
        # This should match HTMLBuilder's inline_labelref behavior
        idref = node.reference_id || content
        %Q(<a target='#{escape_content(idref)}'>「#{I18n.t('label_marker')}#{escape_content(idref)}」</a>)
      end

      def render_inline_ref(type, content, node)
        render_inline_labelref(type, content, node)
      end

      def render_inline_w(_type, content, _node)
        # Content should already be resolved by ReferenceResolver
        content
      end

      def render_inline_wb(_type, content, _node)
        # Content should already be resolved by ReferenceResolver
        %Q(<b>#{content}</b>)
      end

      def render_inline_abbr(_type, content, _node)
        %Q(<abbr>#{content}</abbr>)
      end

      def render_inline_acronym(_type, content, _node)
        %Q(<acronym>#{content}</acronym>)
      end

      def render_inline_cite(_type, content, _node)
        %Q(<cite>#{content}</cite>)
      end

      def render_inline_dfn(_type, content, _node)
        %Q(<dfn>#{content}</dfn>)
      end

      def render_inline_big(_type, content, _node)
        %Q(<big>#{content}</big>)
      end

      def render_inline_small(_type, content, _node)
        %Q(<small>#{content}</small>)
      end

      def render_inline_dtp(_type, content, _node)
        "<?dtp #{content} ?>"
      end

      def render_inline_recipe(_type, content, _node)
        %Q(<span class="recipe">「#{content}」</span>)
      end

      def render_inline_icon(_type, content, node)
        # Icon is an image reference
        id = node.args.first || content
        begin
          %Q(<img src="#{@chapter.image(id).path.sub(%r{\A\./}, '')}" alt="[#{id}]" />)
        rescue ReVIEW::KeyError, NoMethodError
          warn "image not bound: #{id}"
          %Q(<pre>missing image: #{id}</pre>)
        end
      end

      def render_inline_uchar(_type, content, _node)
        %Q(&#x#{content};)
      end

      def render_inline_tcy(_type, content, _node)
        # 縦中横用のtcy、uprightのCSSスタイルについては電書協ガイドラインを参照
        style = 'tcy'
        if content.size == 1 && content.match(/[[:ascii:]]/)
          style = 'upright'
        end
        %Q(<span class="#{style}">#{content}</span>)
      end

      def render_inline_balloon(_type, content, _node)
        %Q(<span class="balloon">#{content}</span>)
      end

      def render_inline_bib(_type, content, node)
        # Bibliography reference
        id = node.args.first || content
        begin
          bib_file = @book.bib_file.gsub(/\.re\Z/, ".#{config['htmlext'] || 'html'}")
          number = @chapter.bibpaper(id).number
          %Q(<a href="#{bib_file}#bib-#{normalize_id(id)}">[#{number}]</a>)
        rescue ReVIEW::KeyError
          %Q([#{id}])
        end
      end

      def render_inline_endnote(_type, content, node)
        # Endnote reference
        id = node.reference_id
        begin
          number = @chapter.endnote(id).number
          %Q(<a id="endnoteb-#{normalize_id(id)}" href="#endnote-#{normalize_id(id)}" class="noteref" epub:type="noteref">#{I18n.t('html_endnote_refmark', number)}</a>)
        rescue ReVIEW::KeyError
          %Q(<a href="#endnote-#{normalize_id(id)}" class="noteref">#{content}</a>)
        end
      end

      def render_inline_eq(_type, content, node)
        # Equation reference
        id = node.reference_id
        begin
          chapter, extracted_id = extract_chapter_id(id)
          equation_number = if get_chap(chapter)
                              %Q(#{I18n.t('equation')}#{I18n.t('format_number', [get_chap(chapter), chapter.equation(extracted_id).number])})
                            else
                              %Q(#{I18n.t('equation')}#{I18n.t('format_number_without_chapter', [chapter.equation(extracted_id).number])})
                            end

          if config['chapterlink']
            %Q(<span class="eqref"><a href="./#{chapter.id}#{extname}##{normalize_id(extracted_id)}">#{equation_number}</a></span>)
          else
            %Q(<span class="eqref">#{equation_number}</span>)
          end
        rescue ReVIEW::KeyError
          %Q(<span class="eqref">#{content}</span>)
        end
      end

      def render_inline_hd(_type, _content, node)
        # Headline reference: @<hd>{id} or @<hd>{chapter|id}
        # This should match HTMLBuilder's inline_hd_chap behavior
        id = node.reference_id
        m = /\A([^|]+)\|(.+)/.match(id)

        chapter = if m && m[1]
                    @book.contents.detect { |chap| chap.id == m[1] }
                  else
                    @chapter
                  end

        headline_id = m ? m[2] : id

        begin
          return '' unless chapter

          n = chapter.headline_index.number(headline_id)
          headline_item = chapter.headline(headline_id)

          # Use caption_node to render caption with inline markup
          caption_html = render_children(headline_item.caption_node)

          str = if n.present? && chapter.number && over_secnolevel?(n, chapter)
                  I18n.t('hd_quote', [n, caption_html])
                else
                  I18n.t('hd_quote_without_number', caption_html)
                end

          if config['chapterlink']
            anchor = 'h' + n.tr('.', '-')
            %Q(<a href="#{chapter.id}#{extname}##{anchor}">#{str}</a>)
          else
            str
          end
        rescue ReVIEW::KeyError
          app_error "unknown headline: #{id}"
        end
      end

      def render_inline_column(_type, _content, node)
        # Column reference: @<column>{id} or @<column>{chapter|id}
        id = node.reference_id
        m = /\A([^|]+)\|(.+)/.match(id)

        chapter = if m && m[1]
                    find_chapter_by_id(m[1])
                  else
                    @chapter
                  end

        column_id = m ? m[2] : id

        begin
          app_error "unknown chapter: #{m[1]}" if m && !chapter
          return '' unless chapter

          column_caption = chapter.column(column_id).caption
          column_number = chapter.column(column_id).number

          anchor = "column-#{column_number}"
          if config['chapterlink']
            %Q(<a href="#{chapter.id}#{extname}##{anchor}" class="columnref">#{I18n.t('column', escape_content(column_caption))}</a>)
          else
            I18n.t('column', escape_content(column_caption))
          end
        rescue ReVIEW::KeyError
          app_error "unknown column: #{column_id}"
        end
      end

      def render_inline_sectitle(_type, content, node)
        # Section title reference
        id = node.reference_id
        begin
          if config['chapterlink']
            chap, id2 = extract_chapter_id(id)
            anchor = 'h' + chap.headline_index.number(id2).tr('.', '-')
            title = chap.headline(id2).caption
            %Q(<a href="#{chap.id}#{extname}##{anchor}">#{escape_content(title)}</a>)
          else
            content
          end
        rescue ReVIEW::KeyError
          content
        end
      end

      def render_inline_pageref(_type, content, _node)
        # Page reference is unsupported in HTML
        content
      end

      # Configuration accessor - returns book config or empty hash for nil safety
      def config
        @book&.config || {}
      end

      # Helper methods for references
      def extract_chapter_id(chap_ref)
        m = /\A([\w+-]+)\|(.+)/.match(chap_ref)
        if m
          ch = find_chapter_by_id(m[1])
          raise ReVIEW::KeyError unless ch

          return [ch, m[2]]
        end
        [@chapter, chap_ref]
      end

      def get_chap(chapter = @chapter)
        if config['secnolevel'] && config['secnolevel'] > 0 &&
           !chapter.number.nil? && !chapter.number.to_s.empty?
          if chapter.is_a?(ReVIEW::Book::Part)
            return I18n.t('part_short', chapter.number)
          else
            return chapter.format_number(nil)
          end
        end
        nil
      end

      def find_chapter_by_id(chapter_id)
        return nil unless @book

        begin
          item = @book.chapter_index[chapter_id]
          return item.content if item.respond_to?(:content)
        rescue ReVIEW::KeyError
          # fall back to contents search
        end

        Array(@book.contents).find { |chap| chap.id == chapter_id }
      end

      def extname
        ".#{config['htmlext'] || 'html'}"
      end

      def over_secnolevel?(n, _chapter = @chapter)
        secnolevel = config['secnolevel'] || 0
        secnolevel >= n.to_s.split('.').size
      end

      private

      # Code block visitors using dynamic method dispatch

      def visit_code_block_emlist(node)
        lines_content = render_children(node)
        processed_content = format_code_content(lines_content, node.lang)

        code_block_wrapper(
          node,
          div_class: 'emlist-code',
          pre_class: build_pre_class('emlist', node.lang),
          content: processed_content,
          caption_style: :top_bottom
        )
      end

      def visit_code_block_emlistnum(node)
        lines_content = render_children(node)
        numbered_lines = format_emlistnum_content(lines_content, node.lang, node)

        code_block_wrapper(
          node,
          div_class: 'emlistnum-code',
          pre_class: build_pre_class('emlist', node.lang),
          content: numbered_lines,
          caption_style: :top_bottom
        )
      end

      def visit_code_block_list(node)
        lines_content = render_children(node)
        processed_content = format_code_content(lines_content, node.lang)

        code_block_wrapper(
          node,
          div_class: 'caption-code',
          pre_class: build_pre_class('list', node.lang),
          content: processed_content,
          caption_style: :numbered
        )
      end

      def visit_code_block_listnum(node)
        lines_content = render_children(node)
        numbered_lines = format_listnum_content(lines_content, node.lang, node)

        code_block_wrapper(
          node,
          div_class: 'code',
          pre_class: build_pre_class('list', node.lang, with_highlight: false),
          content: numbered_lines,
          caption_style: :numbered
        )
      end

      def visit_code_block_source(node)
        lines_content = render_children(node)
        processed_content = format_code_content(lines_content, node.lang)

        code_block_wrapper(
          node,
          div_class: 'source-code',
          pre_class: 'source',
          content: processed_content,
          caption_style: :top_bottom
        )
      end

      def visit_code_block_cmd(node)
        lines_content = render_children(node)
        processed_content = format_code_content(lines_content, node.lang)

        code_block_wrapper(
          node,
          div_class: 'cmd-code',
          pre_class: 'cmd',
          content: processed_content,
          caption_style: :top_bottom
        )
      end

      # render_fallback_code_block removed - Base renderer will raise NotImplementedError for unknown code block types

      def code_block_wrapper(node, div_class:, pre_class:, content:, caption_style:)
        id_attr = node.id ? %Q( id="#{normalize_id(node.id)}") : ''

        caption_top = render_code_caption(node, caption_style, :top)
        caption_bottom = render_code_caption(node, caption_style, :bottom)

        %Q(<div#{id_attr} class="#{div_class}">
#{caption_top}<pre class="#{pre_class}">#{content}</pre>
#{caption_bottom}</div>
)
      end

      def render_code_caption(node, style, position)
        caption_node = node.caption_node
        return '' unless caption_node

        caption_content = render_caption_markup(caption_node)
        return '' if caption_content.empty?

        case style
        when :top_bottom
          return '' unless position == :top ? caption_top?('list') : !caption_top?('list')

          %Q(<p class="caption">#{caption_content}</p>
)
        when :numbered
          return '' unless position == :top

          list_number = generate_list_header(node.id, caption_content)
          %Q(<p class="caption">#{list_number}</p>
)
        else
          ''
        end
      end

      def build_pre_class(base_class, lang, with_highlight: true)
        classes = [base_class]
        classes << "language-#{lang}" if lang
        classes << 'highlight' if with_highlight && highlight?
        classes.join(' ')
      end

      def format_code_content(lines_content, lang = nil)
        lines = lines_content.split("\n")
        body = lines.inject('') { |i, j| i + detab(j) + "\n" }

        highlight(body: body, lexer: lang, format: 'html')
      end

      def format_emlistnum_content(lines_content, lang = nil, node = nil)
        lines = lines_content.split("\n")
        lines.pop if lines.last && lines.last.empty?

        body = lines.inject('') { |i, j| i + detab(j) + "\n" }
        first_line_number = node&.first_line_num || 1

        if highlight?
          highlight(body: body, lexer: lang, format: 'html', linenum: true, options: { linenostart: first_line_number })
        else
          lines.map.with_index(first_line_number) do |line, i|
            "#{i.to_s.rjust(2)}: #{detab(line)}"
          end.join("\n") + "\n"
        end
      end

      def format_listnum_content(lines_content, lang = nil, node = nil)
        lines = lines_content.split("\n")
        lines.pop if lines.last && lines.last.empty?

        body = lines.inject('') { |i, j| i + detab(j) + "\n" }
        first_line_number = node&.first_line_num || 1

        highlighted = highlight(body: body, lexer: lang, format: 'html', linenum: true,
                                options: { linenostart: first_line_number })

        if highlight?
          highlighted
        else
          lines.map.with_index(first_line_number) do |line, i|
            "#{i.to_s.rjust(2)}: #{detab(line)}"
          end.join("\n") + "\n"
        end
      end

      def highlight?
        highlighter.highlight?('html')
      end

      def highlight(body:, lexer: nil, format: 'html', linenum: false, options: {}, location: nil)
        highlighter.highlight(
          body: body,
          lexer: lexer,
          format: format,
          linenum: linenum,
          options: options,
          location: location
        )
      end

      def highlighter
        @highlighter ||= ReVIEW::Highlighter.new(config)
      end

      def generate_list_header(id, caption)
        list_item = @chapter&.list(id)
        raise NotImplementedError, "no such list: #{id}" unless list_item

        list_num = list_item.number
        chapter_num = @chapter&.number

        if chapter_num
          "#{I18n.t('list')}#{I18n.t('format_number_header', [chapter_num, list_num])}#{I18n.t('caption_prefix')}#{caption}"
        else
          "#{I18n.t('list')}#{I18n.t('format_number_header_without_chapter', [list_num])}#{I18n.t('caption_prefix')}#{caption}"
        end
      end

      def visit_reference(node)
        # Handle ReferenceNode - use resolved_data if available
        if node.resolved?
          format_resolved_reference(node.resolved_data)
        else
          node.content || ''
        end
      end

      # Format resolved reference based on ResolvedData
      def format_resolved_reference(data)
        case data
        when AST::ResolvedData::Image
          format_image_reference(data)
        when AST::ResolvedData::Table
          format_table_reference(data)
        when AST::ResolvedData::List
          format_list_reference(data)
        when AST::ResolvedData::Equation
          format_equation_reference(data)
        when AST::ResolvedData::Footnote, AST::ResolvedData::Endnote
          data.item_number.to_s
        when AST::ResolvedData::Chapter
          format_chapter_reference(data)
        when AST::ResolvedData::Headline
          format_headline_reference(data)
        when AST::ResolvedData::Column
          format_column_reference(data)
        when AST::ResolvedData::Word
          escape(data.word_content)
        else
          # Default: return item_id
          escape(data.item_id)
        end
      end

      def format_image_reference(data)
        number_text = if data.chapter_number
                        "#{I18n.t('image')}#{I18n.t('format_number', [data.chapter_number, data.item_number])}"
                      else
                        "#{I18n.t('image')}#{I18n.t('format_number_without_chapter', [data.item_number])}"
                      end

        if config['chapterlink'] && data.cross_chapter?
          %Q(<span class="imgref"><a href="./#{data.chapter_id}#{extname}##{normalize_id(data.item_id)}">#{number_text}</a></span>)
        elsif config['chapterlink']
          %Q(<span class="imgref"><a href="##{normalize_id(data.item_id)}">#{number_text}</a></span>)
        else
          %Q(<span class="imgref">#{number_text}</span>)
        end
      end

      def format_table_reference(data)
        number_text = if data.chapter_number
                        "#{I18n.t('table')}#{I18n.t('format_number', [data.chapter_number, data.item_number])}"
                      else
                        "#{I18n.t('table')}#{I18n.t('format_number_without_chapter', [data.item_number])}"
                      end

        if config['chapterlink'] && data.cross_chapter?
          %Q(<span class="tableref"><a href="./#{data.chapter_id}#{extname}##{normalize_id(data.item_id)}">#{number_text}</a></span>)
        elsif config['chapterlink']
          %Q(<span class="tableref"><a href="##{normalize_id(data.item_id)}">#{number_text}</a></span>)
        else
          %Q(<span class="tableref">#{number_text}</span>)
        end
      end

      def format_list_reference(data)
        number_text = if data.chapter_number
                        "#{I18n.t('list')}#{I18n.t('format_number', [data.chapter_number, data.item_number])}"
                      else
                        "#{I18n.t('list')}#{I18n.t('format_number_without_chapter', [data.item_number])}"
                      end

        if config['chapterlink'] && data.cross_chapter?
          %Q(<span class="listref"><a href="./#{data.chapter_id}#{extname}##{normalize_id(data.item_id)}">#{number_text}</a></span>)
        elsif config['chapterlink']
          %Q(<span class="listref"><a href="##{normalize_id(data.item_id)}">#{number_text}</a></span>)
        else
          %Q(<span class="listref">#{number_text}</span>)
        end
      end

      def format_equation_reference(data)
        number_text = "#{I18n.t('equation')}#{I18n.t('format_number', [data.chapter_number, data.item_number])}"
        if config['chapterlink']
          %Q(<span class="eqref"><a href="##{normalize_id(data.item_id)}">#{number_text}</a></span>)
        else
          %Q(<span class="eqref">#{number_text}</span>)
        end
      end

      def format_chapter_reference(data)
        # For chap and chapref, format based on parent inline type
        if data.chapter_title
          "第#{data.chapter_number}章「#{escape(data.chapter_title)}」"
        else
          "第#{data.chapter_number}章"
        end
      end

      def format_headline_reference(data)
        number_str = data.headline_number.join('.')
        caption = data.headline_caption

        if number_str.empty?
          "「#{escape(caption)}」"
        else
          "#{number_str} #{escape(caption)}"
        end
      end

      def format_column_reference(data)
        "#{I18n.t('column')}#{I18n.t('format_number', [data.chapter_number, data.item_number])}"
      end

      def visit_footnote(node)
        # Handle FootnoteNode - render as footnote or endnote definition
        # Note: This renders the footnote/endnote definition block at document level.
        # For inline footnote references (@<fn>{id}), see render_footnote method.
        footnote_content = render_children(node)

        # Check if this is a footnote or endnote based on footnote_type attribute
        if node.footnote_type == :endnote
          # Endnote - skip rendering here, will be rendered by printendnotes
          return ''
        end

        # Match HTMLBuilder's footnote output format
        footnote_number = @chapter&.footnote(node.id)&.number || '??'

        # Check epubversion for consistent output with HTMLBuilder
        if config['epubversion'].to_i == 3
          # EPUB3 version with epub:type attributes
          # Only add back link if epubmaker/back_footnote is configured (like HTMLBuilder)
          back_link = ''
          if config['epubmaker'] && config['epubmaker']['back_footnote']
            back_link = %Q(<a href="#fnb-#{normalize_id(node.id)}">#{I18n.t('html_footnote_backmark')}</a>)
          end
          %Q(<div class="footnote" epub:type="footnote" id="fn-#{normalize_id(node.id)}"><p class="footnote">#{back_link}#{I18n.t('html_footnote_textmark', footnote_number)}#{footnote_content}</p></div>)
        else
          # Non-EPUB version
          footnote_back_link = %Q(<a href="#fnb-#{normalize_id(node.id)}">*#{footnote_number}</a>)
          %Q(<div class="footnote" id="fn-#{normalize_id(node.id)}"><p class="footnote">[#{footnote_back_link}] #{footnote_content}</p></div>)
        end
      end

      def visit_embed(node)
        # Handle embed blocks and raw commands
        case node.embed_type
        when :raw, :inline
          # Process raw embed content
          process_raw_embed(node)
        else
          # Handle legacy embed blocks
          if node.arg
            # Parse target formats from argument like Builder base class
            builders = node.arg.gsub(/^\s*\|/, '').gsub(/\|\s*$/, '').gsub(/\s/, '').split(',')
            target = target_name

            # Only output if this renderer's target is in the list
            if builders.include?(target)
              content = node.lines.join("\n")
              # For HTML output, ensure XHTML compliance for self-closing tags
              content = ensure_xhtml_compliance(content)
              return content + "\n"
            else
              return ''
            end
          else
            # No format specified, output for all formats
            content = node.lines.join("\n")
            # For HTML output, ensure XHTML compliance for self-closing tags
            content = ensure_xhtml_compliance(content)
            return content + "\n"
          end
        end
      end

      def render_inline_element(type, content, node)
        method_name = "render_inline_#{type}"
        if respond_to?(method_name, true)
          send(method_name, type, content, node)
        else
          raise NotImplementedError, "Unknown inline element: #{type}"
        end
      end

      def render_note_block(node)
        render_callout_block(node, 'note')
      end

      def render_memo_block(node)
        render_callout_block(node, 'memo')
      end

      def render_tip_block(node)
        render_callout_block(node, 'tip')
      end

      def render_info_block(node)
        render_callout_block(node, 'info')
      end

      def render_warning_block(node)
        render_callout_block(node, 'warning')
      end

      def render_important_block(node)
        render_callout_block(node, 'important')
      end

      def render_caution_block(node)
        render_callout_block(node, 'caution')
      end

      def render_notice_block(node)
        render_callout_block(node, 'notice')
      end

      def render_quote_block(node)
        id_attr = node.id ? %Q( id="#{normalize_id(node.id)}") : ''
        content = render_children(node)
        %Q(<blockquote#{id_attr}>#{content}</blockquote>)
      end

      def render_lead_block(node)
        id_attr = node.id ? %Q( id="#{normalize_id(node.id)}") : ''
        content = render_children(node)
        %Q(<div#{id_attr} class="lead">\n#{content}</div>\n)
      end

      def render_comment_block(node)
        # ブロックcomment - draft設定時のみ表示
        return '' unless config['draft']

        content_lines = []

        # 引数があれば最初に追加
        if node.args.first && !node.args.first.empty?
          content_lines << escape(node.args.first)
        end

        # 本文を追加
        if node.content && !node.content.empty?
          body_content = render_children(node)
          content_lines << body_content unless body_content.empty?
        end

        return '' if content_lines.empty?

        content_str = content_lines.join('<br />')
        %Q(<div class="draft-comment">#{content_str}</div>)
      end

      def render_callout_block(node, type)
        id_attr = node.id ? %Q( id="#{normalize_id(node.id)}") : ''

        caption_content = render_caption_markup(node.caption_node)
        caption_html = caption_content.empty? ? '' : %Q(<div class="#{type}-header">#{caption_content}</div>)

        content = render_children(node)

        %Q(<div class="#{type}"#{id_attr}>\n#{caption_html}#{content}</div>)
      end

      def render_generic_block(node)
        id_attr = node.id ? %Q( id="#{normalize_id(node.id)}") : ''
        content = render_children(node)

        %Q(<div class="#{escape(node.block_type)}"#{id_attr}>#{content}</div>)
      end

      # Render label control block
      def render_label_block(node)
        # Extract label from args
        label = node.args.first
        return '' unless label

        %Q(<a id="#{normalize_id(label)}"></a>)
      end

      # Render tsize control block
      def render_tsize_block(_node)
        # Table size control - HTMLBuilder outputs nothing for HTML
        # tsize is only used for LaTeX/PDF output
        ''
      end

      # Render printendnotes control block
      def render_printendnotes_block(_node)
        # Render collected endnotes like HTMLBuilder's printendnotes method
        return '' unless @chapter
        return '' unless @chapter.endnotes

        # Check if there are any endnotes using size
        return '' if @chapter.endnotes.size == 0

        # Mark that we've shown endnotes (like Builder base class)
        @shown_endnotes = true

        # Begin endnotes block
        result = %Q(<div class="endnotes">\n)

        # Render each endnote like HTMLBuilder's endnote_item
        @chapter.endnotes.each do |en|
          back = ''
          if config['epubmaker'] && config['epubmaker']['back_footnote']
            back = %Q(<a href="#endnoteb-#{normalize_id(en.id)}">#{I18n.t('html_footnote_backmark')}</a>)
          end
          # Render endnote content from footnote_node
          endnote_content = render_children(en.footnote_node)
          result += %Q(<div class="endnote" id="endnote-#{normalize_id(en.id)}"><p class="endnote">#{back}#{I18n.t('html_endnote_textmark', @chapter.endnote(en.id).number)}#{endnote_content}</p></div>\n)
        end

        # End endnotes block
        result + %Q(</div>\n)
      end

      # Render flushright block like HTMLBuilder's flushright method
      def render_flushright_block(node)
        # Render children (which produces <p> tags)
        content = render_children(node)
        # Replace <p> with <p class="flushright"> like HTMLBuilder
        content.gsub('<p>', %Q(<p class="flushright">))
      end

      # Render centering block like HTMLBuilder's centering method
      def render_centering_block(node)
        # Render children (which produces <p> tags)
        content = render_children(node)
        # Replace <p> with <p class="center"> like HTMLBuilder
        content.gsub('<p>', %Q(<p class="center">))
      end

      # Render bibpaper block like HTMLBuilder's bibpaper method
      def render_bibpaper_block(node)
        # For BlockNode, id and caption are in args array like HTMLBuilder's bibpaper(lines, id, caption)
        id = node.args[0]
        caption_text = node.args[1]

        # Start div (puts in HTMLBuilder, so newline after)
        result = %Q(<div class="bibpaper">\n)

        # Add anchor and number like HTMLBuilder's bibpaper_header
        # bibpaper_header uses print for anchor, then puts for caption (with newline)
        if id && @chapter
          begin
            bibpaper_number = @chapter.bibpaper(id).number
            result += %Q(<a id="bib-#{normalize_id(id)}">[#{bibpaper_number}]</a> )
          rescue StandardError
            # If bibpaper not found, use ?? like other references
            result += %Q(<a id="bib-#{normalize_id(id)}">[??]</a> )
          end
        end

        # Add caption as plain text (BlockNode doesn't have caption_node)
        # HTMLBuilder uses puts " #{compile_inline(caption)}", so space before caption and newline after
        if caption_text && !caption_text.empty?
          result += escape_content(caption_text) + "\n"
        end

        # Add content wrapped in <p> if present (like split_paragraph does)
        # HTMLBuilder uses print for bibpaper_bibpaper, so no newline after
        # Then puts '</div>' adds the closing tag with newline
        content = render_children(node)
        unless content.strip.empty?
          # strip to remove paragraph newlines, match Builder's behavior
          result += %Q(<p>#{content.strip}</p>)
        end

        # Close div (puts in HTMLBuilder, so it's on the same line as </p>)
        result + "</div>\n"
      end

      def escape(str)
        # Use EscapeUtils for consistency
        escape_content(str.to_s)
      end

      def render_table(id, _node)
        # Generate proper table reference exactly like HTMLBuilder's inline_table method
        table_id = id

        begin
          # Use exactly the same logic as HTMLBuilder's inline_table method
          chapter, extracted_id = extract_chapter_id(table_id)

          # Generate table number using the same pattern as Builder base class
          table_number = if get_chap(chapter)
                           %Q(#{I18n.t('table')}#{I18n.t('format_number', [get_chap(chapter), chapter.table(extracted_id).number])})
                         else
                           %Q(#{I18n.t('table')}#{I18n.t('format_number_without_chapter', [chapter.table(extracted_id).number])})
                         end

          # Generate href exactly like HTMLBuilder with chapterlink check
          if config['chapterlink']
            %Q(<span class="tableref"><a href="./#{chapter.id}#{extname}##{normalize_id(extracted_id)}">#{table_number}</a></span>)
          else
            %Q(<span class="tableref">#{table_number}</span>)
          end
        rescue ReVIEW::KeyError
          # Use app_error for consistency with HTMLBuilder error handling
          app_error("unknown table: #{table_id}")
        end
      end

      # Generate headline prefix and anchor like HTMLBuilder
      def headline_prefix(level)
        return [nil, nil] unless @sec_counter

        @sec_counter.inc(level)
        anchor = @sec_counter.anchor(level)
        prefix = @sec_counter.prefix(level, config['secnolevel'])
        [prefix, anchor]
      end

      # Image helper methods matching HTMLBuilder's implementation
      def image_image_html(id, caption_node, id_attr, image_type = :image)
        caption_html = image_header_html(id, caption_node, image_type)
        caption_present = !caption_html.empty?

        begin
          image_path = @chapter.image(id).path.sub(%r{\A\./}, '')
          alt_text = escape(render_caption_markup(caption_node))

          img_html = %Q(<img src="#{image_path}" alt="#{alt_text}" />)

          # Check caption positioning like HTMLBuilder
          if caption_top?('image') && caption_present
            %Q(<div#{id_attr} class="image">\n#{caption_html}#{img_html}\n</div>\n)
          else
            %Q(<div#{id_attr} class="image">\n#{img_html}\n#{caption_html}</div>\n)
          end
        rescue StandardError
          # If image loading fails, fall back to dummy
          image_dummy_html(id, caption_node, [], id_attr, image_type)
        end
      end

      # Context-aware version of image_image_html
      def image_image_html_with_context(id, caption_node, id_attr, caption_context, image_type = :image)
        caption_html = image_header_html_with_context(id, caption_node, caption_context, image_type)
        caption_present = !caption_html.empty?

        begin
          image_path = @chapter.image(id).path.sub(%r{\A\./}, '')
          img_html = %Q(<img src="#{image_path}" alt="#{escape(render_caption_markup(caption_node))}" />)

          # Check caption positioning like HTMLBuilder
          if caption_top?('image') && caption_present
            %Q(<div#{id_attr} class="image">\n#{caption_html}#{img_html}\n</div>\n)
          else
            %Q(<div#{id_attr} class="image">\n#{img_html}\n#{caption_html}</div>\n)
          end
        rescue StandardError
          # If image loading fails, fall back to dummy
          image_dummy_html_with_context(id, caption_node, [], id_attr, caption_context, image_type)
        end
      end

      def image_dummy_html(id, caption_node, lines, id_attr, image_type = :image)
        caption_html = image_header_html(id, caption_node, image_type)
        caption_present = !caption_html.empty?

        # Generate dummy image content exactly like HTMLBuilder
        # HTMLBuilder puts each line and adds newlines via 'puts'
        lines_content = if lines.empty?
                          "\n" # Empty image block just has one newline
                        else
                          "\n" + lines.map { |line| escape(line) }.join("\n") + "\n"
                        end

        # Check caption positioning like HTMLBuilder
        if caption_top?('image') && caption_present
          %Q(<div#{id_attr} class="image">\n#{caption_html}<pre class="dummyimage">#{lines_content}</pre>\n</div>\n)
        else
          %Q(<div#{id_attr} class="image">\n<pre class="dummyimage">#{lines_content}</pre>\n#{caption_html}</div>\n)
        end
      end

      # Context-aware version of image_dummy_html
      def image_dummy_html_with_context(id, caption_node, lines, id_attr, caption_context, image_type = :image)
        caption_html = image_header_html_with_context(id, caption_node, caption_context, image_type)
        caption_present = !caption_html.empty?

        # Generate dummy image content exactly like HTMLBuilder
        lines_content = if lines.empty?
                          "\n" # Empty image block just has one newline
                        else
                          "\n" + lines.map { |line| escape(line) }.join("\n") + "\n"
                        end

        # Check caption positioning like HTMLBuilder
        if caption_top?('image') && caption_present
          %Q(<div#{id_attr} class="image">\n#{caption_html}<pre class="dummyimage">#{lines_content}</pre>\n</div>\n)
        else
          %Q(<div#{id_attr} class="image">\n<pre class="dummyimage">#{lines_content}</pre>\n#{caption_html}</div>\n)
        end
      end

      def image_header_html(id, caption_node, image_type = :image)
        caption_content = render_caption_markup(caption_node)
        return '' if caption_content.empty?

        # For indepimage (numberless image), use numberless_image label like HTMLBuilder
        if image_type == :indepimage || image_type == :numberlessimage
          image_number = I18n.t('numberless_image')
        else
          # Generate image number like HTMLBuilder using chapter image index
          image_item = @chapter&.image(id)
          unless image_item && image_item.number
            raise ReVIEW::KeyError, "image '#{id}' not found"
          end

          image_number = if get_chap
                           %Q(#{I18n.t('image')}#{I18n.t('format_number_header', [get_chap, image_item.number])})
                         else
                           %Q(#{I18n.t('image')}#{I18n.t('format_number_header_without_chapter', [image_item.number])})
                         end
        end

        %Q(<p class="caption">\n#{image_number}#{I18n.t('caption_prefix')}#{caption_content}\n</p>\n)
      end

      # Context-aware version of image_header_html
      def image_header_html_with_context(id, caption_node, caption_context, image_type = :image)
        caption_content = render_caption_with_context(caption_node, caption_context)
        return '' if caption_content.empty?

        # For indepimage (numberless image), use numberless_image label like HTMLBuilder
        if image_type == :indepimage || image_type == :numberlessimage
          image_number = I18n.t('numberless_image')
        else
          # Generate image number like HTMLBuilder using chapter image index
          image_item = @chapter&.image(id)
          unless image_item && image_item.number
            raise ReVIEW::KeyError, "image '#{id}' not found"
          end

          image_number = if get_chap
                           %Q(#{I18n.t('image')}#{I18n.t('format_number_header', [get_chap, image_item.number])})
                         else
                           %Q(#{I18n.t('image')}#{I18n.t('format_number_header_without_chapter', [image_item.number])})
                         end
        end

        %Q(<p class="caption">\n#{image_number}#{I18n.t('caption_prefix')}#{caption_content}\n</p>\n)
      end

      # Generate table header like HTMLBuilder's table_header method
      def generate_table_header(id, caption)
        table_item = @chapter.table(id)
        table_num = table_item.number
        chapter_num = @chapter.number

        if chapter_num
          "#{I18n.t('table')}#{I18n.t('format_number_header', [chapter_num, table_num])}#{I18n.t('caption_prefix')}#{caption}"
        else
          "#{I18n.t('table')}#{I18n.t('format_number_header_without_chapter', [table_num])}#{I18n.t('caption_prefix')}#{caption}"
        end
      rescue ReVIEW::KeyError
        raise NotImplementedError, "no such table: #{id}"
      end

      # Render imgtable (table as image) like HTMLBuilder's imgtable method
      def render_imgtable(node)
        id = node.id
        caption_node = node.caption_node

        # Check if image is bound like HTMLBuilder does
        unless @chapter&.image_bound?(id)
          warn "image not bound: #{id}"
          # For dummy images, use empty array for lines (no lines in TableNode)
          return render_imgtable_dummy(id, caption_node, [])
        end

        id_attr = id ? %Q( id="#{normalize_id(id)}") : ''

        # Generate table caption HTML if caption exists
        caption_content = render_caption_markup(caption_node)
        caption_html = if caption_content.empty?
                         ''
                       else
                         table_caption = generate_table_header(id, caption_content)
                         %Q(<p class="caption">#{table_caption}</p>\n)
                       end

        # Render image tag
        begin
          image_path = @chapter.image(id).path.sub(%r{\A\./}, '')
          alt_text = escape(caption_plain_text(caption_node))
          img_html = %Q(<img src="#{image_path}" alt="#{alt_text}" />\n)

          # Check caption positioning like HTMLBuilder (uses 'table' type for imgtable)
          if caption_top?('table') && !caption_content.empty?
            %Q(<div#{id_attr} class="imgtable image">\n#{caption_html}#{img_html}</div>\n)
          else
            %Q(<div#{id_attr} class="imgtable image">\n#{img_html}#{caption_html}</div>\n)
          end
        rescue ReVIEW::KeyError
          app_error "no such table: #{id}"
        end
      end

      # Render dummy imgtable when image is not found
      def render_imgtable_dummy(id, caption_node, lines)
        id_attr = id ? %Q( id="#{normalize_id(id)}") : ''

        # Generate table caption HTML if caption exists
        caption_content = render_caption_markup(caption_node)
        caption_html = if caption_content.empty?
                         ''
                       else
                         table_caption = generate_table_header(id, caption_content)
                         %Q(<p class="caption">#{table_caption}</p>\n)
                       end

        # Generate dummy content like image_dummy_html
        lines_content = if lines.empty?
                          "\n"
                        else
                          "\n" + lines.map { |line| escape(line) }.join("\n") + "\n"
                        end

        # Check caption positioning like HTMLBuilder
        if caption_top?('table') && !caption_content.empty?
          %Q(<div#{id_attr} class="imgtable image">\n#{caption_html}<pre class="dummyimage">#{lines_content}</pre>\n</div>\n)
        else
          %Q(<div#{id_attr} class="imgtable image">\n<pre class="dummyimage">#{lines_content}</pre>\n#{caption_html}</div>\n)
        end
      end

      # Generate indexes using AST::Indexer for Renderer (builder-independent)
      def generate_ast_indexes(ast_node)
        return if @ast_indexes_generated

        # Check if indexes are already generated on the AST node
        if ast_node.is_a?(ReVIEW::AST::DocumentNode) && ast_node.indexes_generated
          @ast_indexes_generated = true
          return
        end

        if @chapter
          # Use AST::Indexer to generate indexes directly from AST
          @ast_indexer = ReVIEW::AST::Indexer.new(@chapter)
          @ast_indexer.build_indexes(ast_node)
        end

        # Generate book-level indexes if book is available
        # This handles bib files and chapter index creation
        if @book && @book.respond_to?(:generate_indexes)
          @book.generate_indexes
        end

        @ast_indexes_generated = true
      end

      def render_caption_markup(caption_node)
        return '' unless caption_node

        content = render_children(caption_node)
        # Join lines like visit_paragraph does
        join_paragraph_lines(content)
      end

      def render_caption_with_context(caption_node, caption_context)
        return '' unless caption_node

        render_children_with_context(caption_node, caption_context)
      end

      def caption_plain_text(caption_node)
        caption_node&.to_text.to_s
      end

      # Process raw embed content (//raw and @<raw>)
      def process_raw_embed(node)
        # Check if content should be output for this renderer
        return '' unless node.targeted_for?('html')

        # Get processed content and convert \\n to actual newlines
        content = node.content || ''
        processed_content = content.gsub('\\n', "\n")

        # Apply XHTML compliance for HTML output
        ensure_xhtml_compliance(processed_content)
      end

      # Ensure XHTML compliance for self-closing tags
      def ensure_xhtml_compliance(content)
        content.gsub(/<hr(\s[^>]*)?>/, '<hr\1 />').
          gsub(/<br(\s[^>]*)?>/, '<br\1 />').
          gsub(%r{<img([^>]*[^/])>}, '<img\1 />').
          gsub(%r{<input([^>]*[^/])>}, '<input\1 />')
      end

      # Builder compatibility - return target name for embed blocks
      def target_name
        'html'
      end

      # Render children with specific rendering context
      def render_children_with_context(node, context)
        old_context = @rendering_context
        @rendering_context = context
        result = render_children(node)
        @rendering_context = old_context
        result
      end

      # Visit node with specific rendering context
      def visit_with_context(node, context)
        old_context = @rendering_context
        @rendering_context = context
        result = visit(node)
        @rendering_context = old_context
        result
      end
    end
  end
end
