---
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
build_script:
  - bundle install
  - bundle exec rake test --trace --verbose
  - bundle exec rubocop

before_test:
  - gem install -N epubcheck-ruby

test_script:
  - ruby bin/review-init hello
  - cd hello
  - ruby ../bin/review-epubmaker config.yml
  - epubcheck book.epub
  - cd ..
  - ruby bin/review-init hello2 --epub-version 2
  - cd hello2
  - ruby ../bin/review-epubmaker config.yml
  - epubcheck book.epub

branches:
  only:
    - master

environment:
  matrix:
    - ruby_version: "24"
    - ruby_version: "24-x64"
    - ruby_version: "25"
    - ruby_version: "25-x64"
    - ruby_version: "26"
    - ruby_version: "26-x64"
