# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "review"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["kmuto", "takahashim"]
  s.date = "2013-03-09"
  s.description = "ReVIEW is a digital publishing system for books and ebooks. It supports InDesign, EPUB and LaTeX."
  s.email = "kmuto@debian.org"
  s.executables = ["review-check", "review-checkdep", "review-compile", "review-epubmaker", "review-epubmaker-ng", "review-index", "review-init", "review-pdfmaker", "review-preproc", "review-validate", "review-vol"]
  s.extra_rdoc_files = [
    "ChangeLog",
    "README.rdoc"
  ]
  s.files = [
    ".travis.yml",
    "COPYING",
    "ChangeLog",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/review-check",
    "bin/review-checkdep",
    "bin/review-compile",
    "bin/review-epubmaker",
    "bin/review-epubmaker-ng",
    "bin/review-index",
    "bin/review-init",
    "bin/review-pdfmaker",
    "bin/review-preproc",
    "bin/review-validate",
    "bin/review-vol",
    "debian/README.Debian",
    "debian/README.source",
    "debian/changelog",
    "debian/compat",
    "debian/control",
    "debian/copyright",
    "debian/docs",
    "debian/manpage.1.ex",
    "debian/patches/path.diff",
    "debian/patches/series",
    "debian/review.install",
    "debian/review.links",
    "debian/rules",
    "debian/source/format",
    "doc/format.rdoc",
    "doc/format_idg.rdoc",
    "doc/libepubmaker/sample.yaml",
    "doc/quickstart.rdoc",
    "doc/ruby-uuid/README",
    "doc/ruby-uuid/README.ja",
    "doc/sample.css",
    "doc/sample.yaml",
    "lib/epubmaker.rb",
    "lib/epubmaker/content.rb",
    "lib/epubmaker/epubv2.rb",
    "lib/epubmaker/epubv3.rb",
    "lib/epubmaker/producer.rb",
    "lib/epubmaker/resource.rb",
    "lib/lineinput.rb",
    "lib/review.rb",
    "lib/review/book.rb",
    "lib/review/book/base.rb",
    "lib/review/book/chapter.rb",
    "lib/review/book/compilable.rb",
    "lib/review/book/index.rb",
    "lib/review/book/page_metric.rb",
    "lib/review/book/parameters.rb",
    "lib/review/book/part.rb",
    "lib/review/book/volume.rb",
    "lib/review/builder.rb",
    "lib/review/compiler.rb",
    "lib/review/configure.rb",
    "lib/review/epubbuilder.rb",
    "lib/review/ewbbuilder.rb",
    "lib/review/exception.rb",
    "lib/review/extentions.rb",
    "lib/review/extentions/object.rb",
    "lib/review/extentions/string.rb",
    "lib/review/htmlbuilder.rb",
    "lib/review/htmllayout.rb",
    "lib/review/htmlutils.rb",
    "lib/review/i18n.rb",
    "lib/review/i18n.yaml",
    "lib/review/idgxmlbuilder.rb",
    "lib/review/inaobuilder.rb",
    "lib/review/latexbuilder.rb",
    "lib/review/latexindex.rb",
    "lib/review/latexutils.rb",
    "lib/review/makerhelper.rb",
    "lib/review/preprocessor.rb",
    "lib/review/review.tex.erb",
    "lib/review/textbuilder.rb",
    "lib/review/textutils.rb",
    "lib/review/tocparser.rb",
    "lib/review/tocprinter.rb",
    "lib/review/topbuilder.rb",
    "lib/review/unfold.rb",
    "lib/uuid.rb",
    "review.gemspec",
    "test/CHAPS",
    "test/bib.re",
    "test/book_test_helper.rb",
    "test/sample-book/README.md",
    "test/sample-book/src/CHAPS",
    "test/sample-book/src/PREDEF",
    "test/sample-book/src/Rakefile",
    "test/sample-book/src/_cover.html",
    "test/sample-book/src/ch01.re",
    "test/sample-book/src/ch02.re",
    "test/sample-book/src/config.yml",
    "test/sample-book/src/images/ch01-imgsample.jpg",
    "test/sample-book/src/images/cover.jpg",
    "test/sample-book/src/main.css",
    "test/sample-book/src/preface.re",
    "test/sample-book/src/sty/jumoline.sty",
    "test/sample-book/src/sty/samplemacro.sty",
    "test/test.re",
    "test/test_book.rb",
    "test/test_book_chapter.rb",
    "test/test_book_parameter.rb",
    "test/test_book_part.rb",
    "test/test_builder.rb",
    "test/test_compiler.rb",
    "test/test_epubmaker.rb",
    "test/test_epubmaker_cmd.rb",
    "test/test_helper.rb",
    "test/test_htmlbuilder.rb",
    "test/test_htmlutils.rb",
    "test/test_i18n.rb",
    "test/test_idgxmlbuilder.rb",
    "test/test_inaobuilder.rb",
    "test/test_index.rb",
    "test/test_latexbuilder.rb",
    "test/test_lineinput.rb",
    "test/test_makerhelper.rb",
    "test/test_pdfmaker_cmd.rb",
    "test/test_preprocessor.rb",
    "test/test_textutils.rb",
    "test/test_topbuilder.rb",
    "test/test_uuid.rb"
  ]
  s.homepage = "http://github.com/kmuto/review"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "ReVIEW: a easy-to-use digital publishing system"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

